### ISSUE TITLE
[RTSP] It canNOT be pushed by Larix Broadcaster app to stream

### ISSUE THREAD

**Issue by iesvme** [aler9/rtsp-simple-server#819] opened 2022-02-09 13:42 UTC
## Which version are you using?

v0.17.16

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue
[RTSP] It canNOT be pushed by Larix Broadcaster app to stream.  (Android 10) 
Larix Broadcaster https://softvelum.com/larix/

## Describe how to replicate the issue

rtsp-simple-server.yml
 publishUser: aaa
 publishPass: 123456
1. start the server
2. publish with Larix Broadcaster (Android 10) {
   URL: rtsp://192.168.10.11:8554/0
   Login: aaa
   Password: 123456
}

## Did you attach the server logs?

2022/02/10 20:31:35 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2022/02/10 20:31:35 INF [RTMP] listener opened on :1935
2022/02/10 20:31:35 INF [HLS] listener opened on :8888
2022/02/10 20:31:36 INF [RTSP] [conn 192.168.10.101:39215] opened
2022/02/10 20:31:36 INF [RTSP] [session 963524608] opened by 192.168.10.101:39215
2022/02/10 20:31:36 INF [RTSP] [session 751978826] opened by 192.168.10.101:39215
2022/02/10 20:31:36 INF [RTSP] [session 612576414] opened by 192.168.10.101:39215
2022/02/10 20:31:36 INF [RTSP] [conn 192.168.10.101:39215] closed (invalid track path (0/streamid=0))
2022/02/10 20:31:36 INF [RTSP] [session 963524608] closed (not in use)
2022/02/10 20:31:36 INF [RTSP] [session 612576414] closed (not in use)
2022/02/10 20:31:36 INF [RTSP] [session 751978826] closed (not in use)
2022/02/10 20:31:40 INF [RTSP] [conn 192.168.10.101:39217] opened
2022/02/10 20:31:40 INF [RTSP] [session 256573366] opened by 192.168.10.101:39217
2022/02/10 20:31:40 INF [RTSP] [session 192571746] opened by 192.168.10.101:39217
2022/02/10 20:31:40 INF [RTSP] [session 822598395] opened by 192.168.10.101:39217
2022/02/10 20:31:40 INF [RTSP] [conn 192.168.10.101:39217] closed (invalid track path (0/streamid=0))
2022/02/10 20:31:40 INF [RTSP] [session 822598395] closed (not in use)
2022/02/10 20:31:40 INF [RTSP] [session 256573366] closed (not in use)
2022/02/10 20:31:40 INF [RTSP] [session 192571746] closed (not in use)

**Comment by iesvme** [comment] 2022-02-09 15:45
change url: live/live is ok.

**Comment by aler9** [comment] 2022-02-10 15:15
duplicate of #815

**Closed by aler9** 2022-02-10 15:15 UTC
