### ISSUE TITLE
[HLS] The video could't fast-reverse by double-clicking.

### ISSUE THREAD

**Issue by iesvme** [aler9/rtsp-simple-server#782] opened 2022-01-20 13:31 UTC
## Which version are you using?

v0.17.14

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

[HLS] The video could't fast-reverse by double-clicking.

## Describe how to replicate the issue

1. start the server
2. publish with obs by rtsp
3. read with HLS by Android
4. double-click multiple times on the right side of video
5. double-click multiple times on the left side of video
6. the video could't fast-reverse by double-clicking

**Comment by aler9** [comment] 2022-01-27 22:24
duplicate of #776

**Closed by aler9** 2022-01-27 22:24 UTC
