### ISSUE TITLE
"Fallback" redirect not working

### ISSUE THREAD

**Issue by MrCheatEugene** [aler9/rtsp-simple-server#1381] opened 2023-01-15 19:14 UTC
## Which version are you using?

v0.20.2

## Which operating system are you using?

- [x] Linux amd64 standard
- [x] Ubuntu 22.04 LTS

## Describe the issue

I need to redirect users to another stream, when main is not avaliable. It seems like it is possible with "fallback", but when I set it to anything, it just does not work.

## Describe how to replicate the issue

1. install server
2. set "fallback" in paths:all to /silence
3. start server
4. publish with FFMpeg to path /silence (ffmpeg -stream_loop -1 -re" -i silence.mp3 -map 0:a -c copy -f rtsp -c:a aac rtsp://localhost:8554/silence), where silence.mp3 can be any mediafile, I used some mp3s from github for that
5. open http://localhost:8888/mystream (use port, that you use for HLS, for me it's 8888)
6. it should shot 404 instead of silent stream

## Did you attach the server logs?
no

## Did you attach a network dump?
no

**Comment by aler9** [comment] 2023-01-24 18:41
duplicate of #1007

**Closed by aler9** 2023-01-24 18:41 UTC
