### ISSUE TITLE
Add options to Rot90 and Transpose the image

### ISSUE THREAD

**Issue by dudududodododedede** [aler9/rtsp-simple-server#1276] opened 2022-12-05 03:51 UTC
## Describe the feature

rtsp-simple-server already supports VFlip and HFlip (booleans) from libcamera but would be amazing if it also support Rot90 and Transpose from libcamera:

https://libcamera.org/api-html/namespacelibcamera.html#a371b6d17d531b85c035c4e889b116571ad5251a97af7b4036b4528a54405ea2ad

https://libcamera.org/api-html/namespacelibcamera.html#a371b6d17d531b85c035c4e889b116571aaf70b1ac863830a4e1ce6268c8399f54

**Comment by aler9** [comment] 2023-01-08 21:54
duplicate of #1285

**Closed by aler9** 2023-01-08 21:54 UTC
