### ISSUE TITLE
Server returned 404 Not Found after a while

### ISSUE THREAD

**Issue by arkanoid87** [aler9/rtsp-simple-server#171] opened 2020-12-29 03:43 UTC
## Which version are you using?

HEAD

## Which operating system are you using?

OS

- [x] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [ ] amd64
- [ ] arm64
- [ ] arm7
- [x] arm6

## Describe the problem

I'm using rtspclientsink + rtsp-simple-server to distribute live stream

GSTREAMER (partial pipeline)
`rtspclientsink name=rtsp location=rtsp://localhost:8554/stream sink_0::payloader="rtph264pay0 mtu=1234" sink_1::payloader="rtpmp4gpay mtu=1234" video. ! queue ! rtsp.sink_0 audio. ! queue ! rtsp.sink_1`

where audio and video are tees next to avenc_aac and x264enc. I'm using the tees to also mux and save stream to disk

RTSP-SIMPLE-SERVER
`RTSP_RTSPPORT=8554 RTSP_PATHS_ALL_READUSER=foo RTSP_PATHS_ALL_READPASS=bar rtsp-simple-server`

Once launched, it works. ffplay and other clients can connect both via tcp and udp using password and it works nicely (A/V/RTCP everything is ok), but after a while (~1h, still testing this, will edit later) the stream stops being served and 404 Not Found is returned instead.

rtps-simple-server log:
```
[2/0/0] [client 192.168.1.100:53982] connected (plain)                                                                                                      
[2/0/0] [client 192.168.1.100::53982] no one is publishing to path 'stream'                                                                                  
[1/0/0] [client 192.168.1.100::53982] disconnected 
```

openRTSP output:
```
Received 54 new bytes of response data.
Received a complete DESCRIBE response:
RTSP/1.0 404 Not Found
CSeq: 4
Server: gortsplib
```

Gstreamer logs:
```
...
Dec 29 04:46:55 fd44a958 rec[6423]: /GstPipeline:pipeline0/GstRTSPClientSink:rtsp/GstBin:rtspbin/GstRtpBin:rtpbin0/GstRtpSession:rtpsession1: stats = application/x-rtp-session-stats, rtx-drop-count=(uint)0, sent-nack-count=(uint)0, recv-nack-count=(uint)0, source-stats=(GValueArray)< "application/x-rtp-source-stats\,\ ssrc\=\(uint\)1429096\,\ internal\=\(boolean\)true\,\ validated\=\(boolean\)true\,\ received-bye\=\(boolean\)false\,\ is-csrc\=\(boolean\)false\,\ is-sender\=\(boolean\)true\,\ seqnum-base\=\(int\)7776\,\ clock-rate\=\(int\)90000\,\ octets-sent\=\(guint64\)1384665017\,\ packets-sent\=\(guint64\)2827432\,\ octets-received\=\(guint64\)1384665017\,\ packets-received\=\(guint64\)2675320\,\ bitrate\=\(guint64\)247011\,\ packets-lost\=\(int\)-2675320\,\ jitter\=\(uint\)0\,\ sent-pli-count\=\(uint\)0\,\ recv-pli-count\=\(uint\)0\,\ sent-fir-count\=\(uint\)0\,\ recv-fir-count\=\(uint\)0\,\ sent-nack-count\=\(uint\)0\,\ recv-nack-count\=\(uint\)0\,\ have-sr\=\(boolean\)true\,\ sr-ntptime\=\(guint64\)16399054504491079023\,\ sr-rtptime\=\(uint\)2872084282\,\ sr-octet-count\=\(uint\)1384665017\,\ sr-packet-count\=\(uint\)2827432\;" >, rtx-count=(uint)0;                                                                                            
Dec 29 04:46:57 fd44a958 rec[6423]: /GstPipeline:pipeline0/GstRTSPClientSink:rtsp/GstBin:rtspbin/GstRtpBin:rtpbin0/GstRtpSession:rtpsession0: stats = application/x-rtp-session-stats, rtx-drop-count=(uint)0, sent-nack-count=(uint)0, recv-nack-count=(uint)0, source-stats=(GValueArray)< "application/x-rtp-source-stats\,\ ssrc\=\(uint\)3704260737\,\ internal\=\(boolean\)true\,\ validated\=\(boolean\)true\,\ received-bye\=\(boolean\)false\,\ is-csrc\=\(boolean\)false\,\ is-sender\=\(boolean\)true\,\ seqnum-base\=\(int\)3903\,\ clock-rate\=\(int\)22050\,\ octets-sent\=\(guint64\)355675400\,\ packets-sent\=\(guint64\)943936\,\ octets-received\=\(guint64\)355675400\,\ packets-received\=\(guint64\)943936\,\ bitrate\=\(guint64\)64888\,\ packets-lost\=\(int\)-943936\,\ jitter\=\(uint\)0\,\ sent-pli-count\=\(uint\)0\,\ recv-pli-count\=\(uint\)0\,\ sent-fir-count\=\(uint\)0\,\ recv-fir-count\=\(uint\)0\,\ sent-nack-count\=\(uint\)0\,\ recv-nack-count\=\(uint\)0\,\ have-sr\=\(boolean\)true\,\ sr-ntptime\=\(guint64\)16399054510684250065\,\ sr-rtptime\=\(uint\)594661962\,\ sr-octet-count\=\(uint\)355675400\,\ sr-packet-count\=\(uint\)943936\;" >, rtx-count=(uint)0;                                                                                                  
Dec 29 04:46:58 fd44a958 rec[6423]: /GstPipeline:pipeline0/GstRTSPClientSink:rtsp/GstBin:rtspbin/GstRtpBin:rtpbin0/GstRtpSession:rtpsession1: stats = application/x-rtp-session-stats, rtx-drop-count=(uint)0, sent-nack-count=(uint)0, recv-nack-count=(uint)0, source-stats=(GValueArray)< "application/x-rtp-source-stats\,\ ssrc\=\(uint\)1429096\,\ internal\=\(boolean\)true\,\ validated\=\(boolean\)true\,\ received-bye\=\(boolean\)false\,\ is-csrc\=\(boolean\)false\,\ is-sender\=\(boolean\)true\,\ seqnum-base\=\(int\)7776\,\ clock-rate\=\(int\)90000\,\ octets-sent\=\(guint64\)1384769439\,\ packets-sent\=\(guint64\)2827638\,\ octets-received\=\(guint64\)1384769439\,\ packets-received\=\(guint64\)2675514\,\ bitrate\=\(guint64\)249259\,\ packets-lost\=\(int\)-2675514\,\ jitter\=\(uint\)0\,\ sent-pli-count\=\(uint\)0\,\ recv-pli-count\=\(uint\)0\,\ sent-fir-count\=\(uint\)0\,\ recv-fir-count\=\(uint\)0\,\ sent-nack-count\=\(uint\)0\,\ recv-nack-count\=\(uint\)0\,\ have-sr\=\(boolean\)true\,\ sr-ntptime\=\(guint64\)16399054504491079023\,\ sr-rtptime\=\(uint\)2872084282\,\ sr-octet-count\=\(uint\)1384665017\,\ sr-packet-count\=\(uint\)2827432\;" >, rtx-count=(uint)0;                                                                                            
Dec 29 04:46:59 fd44a958 rec[6423]: /GstPipeline:pipeline0/GstRTSPClientSink:rtsp/GstBin:rtspbin/GstRtpBin:rtpbin0/GstRtpSession:rtpsession0: stats = application/x-rtp-session-stats, rtx-drop-count=(uint)0, sent-nack-count=(uint)0, recv-nack-count=(uint)0, source-stats=(GValueArray)< "application/x-rtp-source-stats\,\ ssrc\=\(uint\)3704260737\,\ internal\=\(boolean\)true\,\ validated\=\(boolean\)true\,\ received-bye\=\(boolean\)false\,\ is-csrc\=\(boolean\)false\,\ is-sender\=\(boolean\)true\,\ seqnum-base\=\(int\)3903\,\ clock-rate\=\(int\)22050\,\ octets-sent\=\(guint64\)355692709\,\ packets-sent\=\(guint64\)943982\,\ octets-received\=\(guint64\)355692709\,\ packets-received\=\(guint64\)943982\,\ bitrate\=\(guint64\)64889\,\ packets-lost\=\(int\)-943982\,\ jitter\=\(uint\)0\,\ sent-pli-count\=\(uint\)0\,\ recv-pli-count\=\(uint\)0\,\ sent-fir-count\=\(uint\)0\,\ recv-fir-count\=\(uint\)0\,\ sent-nack-count\=\(uint\)0\,\ recv-nack-count\=\(uint\)0\,\ have-sr\=\(boolean\)true\,\ sr-ntptime\=\(guint64\)16399054510684250065\,\ sr-rtptime\=\(uint\)594661962\,\ sr-octet-count\=\(uint\)355675400\,\ sr-packet-count\=\(uint\)943936\;" >, rtx-count=(uint)0;                                                                                                  
Dec 29 04:46:59 fd44a958 rec[6423]: /GstPipeline:pipeline0/GstRTSPClientSink:rtsp/GstBin:rtspbin/GstRtpBin:rtpbin0/GstRtpSession:rtpsession1: stats = application/x-rtp-session-stats, rtx-drop-count=(uint)0, sent-nack-count=(uint)0, recv-nack-count=(uint)0, source-stats=(GValueArray)< "application/x-rtp-source-stats\,\ ssrc\=\(uint\)1429096\,\ internal\=\(boolean\)true\,\ validated\=\(boolean\)true\,\ received-bye\=\(boolean\)false\,\ is-csrc\=\(boolean\)false\,\ is-sender\=\(boolean\)true\,\ seqnum-base\=\(int\)7776\,\ clock-rate\=\(int\)90000\,\ octets-sent\=\(guint64\)1384793682\,\ packets-sent\=\(guint64\)2827692\,\ octets-received\=\(guint64\)1384793682\,\ packets-received\=\(guint64\)2675568\,\ bitrate\=\(guint64\)249259\,\ packets-lost\=\(int\)-2675568\,\ jitter\=\(uint\)0\,\ sent-pli-count\=\(uint\)0\,\ recv-pli-count\=\(uint\)0\,\ sent-fir-count\=\(uint\)0\,\ recv-fir-count\=\(uint\)0\,\ sent-nack-count\=\(uint\)0\,\ recv-nack-count\=\(uint\)0\,\ have-sr\=\(boolean\)true\,\ sr-ntptime\=\(guint64\)16399054504491079023\,\ sr-rtptime\=\(uint\)2872084282\,\ sr-octet-count\=\(uint\)1384665017\,\ sr-packet-count\=\(uint\)2827432\;" >, rtx-count=(uint)0;                                                                                            
Dec 29 04:47:00 fd44a958 rec[6423]: /GstPipeline:pipeline0/GstRTSPClientSink:rtsp/GstBin:rtspbin/GstRtpBin:rtpbin0/GstRtpSession:rtpsession1: stats = application/x-rtp-session-stats, rtx-drop-count=(uint)0, sent-nack-count=(uint)0, recv-nack-count=(uint)0, source-stats=(GValueArray)< "application/x-rtp-source-stats\,\ ssrc\=\(uint\)1429096\,\ internal\=\(boolean\)true\,\ validated\=\(boolean\)true\,\ received-bye\=\(boolean\)false\,\ is-csrc\=\(boolean\)false\,\ is-sender\=\(boolean\)true\,\ seqnum-base\=\(int\)7776\,\ clock-rate\=\(int\)90000\,\ octets-sent\=\(guint64\)1384839973\,\ packets-sent\=\(guint64\)2827777\,\ octets-received\=\(guint64\)1384839973\,\ packets-received\=\(guint64\)2675648\,\ bitrate\=\(guint64\)250819\,\ packets-lost\=\(int\)-2675648\,\ jitter\=\(uint\)0\,\ sent-pli-count\=\(uint\)0\,\ recv-pli-count\=\(uint\)0\,\ sent-fir-count\=\(uint\)0\,\ recv-fir-count\=\(uint\)0\,\ sent-nack-count\=\(uint\)0\,\ recv-nack-count\=\(uint\)0\,\ have-sr\=\(boolean\)true\,\ sr-ntptime\=\(guint64\)16399054527479552172\,\ sr-rtptime\=\(uint\)2872566037\,\ sr-octet-count\=\(uint\)1384839973\,\ sr-packet-count\=\(uint\)2827777\;" >, rtx-count=(uint)0;                                                                                            
Dec 29 04:47:01 fd44a958 rec[6423]: /GstPipeline:pipeline0/GstRTSPClientSink:rtsp/GstBin:rtspbin/GstRtpBin:rtpbin0/GstRtpSession:rtpsession0: stats = application/x-rtp-session-stats, rtx-drop-count=(uint)0, sent-nack-count=(uint)0, recv-nack-count=(uint)0, source-stats=(GValueArray)< "application/x-rtp-source-stats\,\ ssrc\=\(uint\)3704260737\,\ internal\=\(boolean\)true\,\ validated\=\(boolean\)true\,\ received-bye\=\(boolean\)false\,\ is-csrc\=\(boolean\)false\,\ is-sender\=\(boolean\)true\,\ seqnum-base\=\(int\)3903\,\ clock-rate\=\(int\)22050\,\ octets-sent\=\(guint64\)355712686\,\ packets-sent\=\(guint64\)944035\,\ octets-received\=\(guint64\)355712686\,\ packets-received\=\(guint64\)944035\,\ bitrate\=\(guint64\)64943\,\ packets-lost\=\(int\)-944035\,\ jitter\=\(uint\)0\,\ sent-pli-count\=\(uint\)0\,\ recv-pli-count\=\(uint\)0\,\ sent-fir-count\=\(uint\)0\,\ recv-fir-count\=\(uint\)0\,\ sent-nack-count\=\(uint\)0\,\ recv-nack-count\=\(uint\)0\,\ have-sr\=\(boolean\)true\,\ sr-ntptime\=\(guint64\)16399054510684250065\,\ sr-rtptime\=\(uint\)594661962\,\ sr-octet-count\=\(uint\)355675400\,\ sr-packet-count\=\(uint\)943936\;" >, rtx-count=(uint)0;                                                                                                  
Dec 29 04:47:02 fd44a958 rec[6423]: /GstPipeline:pipeline0/GstRTSPClientSink:rtsp/GstBin:rtspbin/GstRtpBin:rtpbin0/GstRtpSession:rtpsession0: stats = application/x-rtp-session-stats, rtx-drop-count=(uint)0, sent-nack-count=(uint)0, recv-nack-count=(uint)0, source-stats=(GValueArray)< "application/x-rtp-source-stats\,\ ssrc\=\(uint\)3704260737\,\ internal\=\(boolean\)true\,\ validated\=\(boolean\)true\,\ received-bye\=\(boolean\)false\,\ is-csrc\=\(boolean\)false\,\ is-sender\=\(boolean\)true\,\ seqnum-base\=\(int\)3903\,\ clock-rate\=\(int\)22050\,\ octets-sent\=\(guint64\)355723289\,\ packets-sent\=\(guint64\)944063\,\ octets-received\=\(guint64\)355723289\,\ packets-received\=\(guint64\)944063\,\ bitrate\=\(guint64\)64943\,\ packets-lost\=\(int\)-944063\,\ jitter\=\(uint\)0\,\ sent-pli-count\=\(uint\)0\,\ recv-pli-count\=\(uint\)0\,\ sent-fir-count\=\(uint\)0\,\ recv-fir-count\=\(uint\)0\,\ sent-nack-count\=\(uint\)0\,\ recv-nack-count\=\(uint\)0\,\ have-sr\=\(boolean\)true\,\ sr-ntptime\=\(guint64\)16399054510684250065\,\ sr-rtptime\=\(uint\)594661962\,\ sr-octet-count\=\(uint\)355675400\,\ sr-packet-count\=\(uint\)943936\;" >, rtx-count=(uint)0;
Dec 29 04:47:03 fd44a958 rec[6423]: /GstPipeline:pipeline0/GstRTSPClientSink:rtsp/GstBin:rtspbin/GstRtpBin:rtpbin0/GstRtpSession:rtpsession0: stats = application/x-rtp-session-stats, rtx-drop-count=(uint)0, sent-nack-count=(uint)0, recv-nack-count=(uint)0, source-stats=(GValueArray)< "application/x-rtp-source-stats\,\ ssrc\=\(uint\)3704260737\,\ internal\=\(boolean\)true\,\ validated\=\(boolean\)true\,\ received-bye\=\(boolean\)false\,\ is-csrc\=\(boolean\)false\,\ is-sender\=\(boolean\)true\,\ seqnum-base\=\(int\)3903\,\ clock-rate\=\(int\)22050\,\ octets-sent\=\(guint64\)355724379\,\ packets-sent\=\(guint64\)944066\,\ octets-received\=\(guint64\)355724379\,\ packets-received\=\(guint64\)944066\,\ bitrate\=\(guint64\)64925\,\ packets-lost\=\(int\)-944066\,\ jitter\=\(uint\)0\,\ sent-pli-count\=\(uint\)0\,\ recv-pli-count\=\(uint\)0\,\ sent-fir-count\=\(uint\)0\,\ recv-fir-count\=\(uint\)0\,\ sent-nack-count\=\(uint\)0\,\ recv-nack-count\=\(uint\)0\,\ have-sr\=\(boolean\)true\,\ sr-ntptime\=\(guint64\)16399054536805545374\,\ sr-rtptime\=\(uint\)594795964\,\ sr-octet-count\=\(uint\)355724379\,\ sr-packet-count\=\(uint\)944066\;" >, rtx-count=(uint)0;
...
```

## Did you attach a network dump?

yes

captured while I get 404 Not Found when I try to connect

network dump shows:
- a continue flow of rtp/udp packets from multiple gst ports to rtsp-simple-server port 8000
- sr/udp from multiple gst ports to rtsp-simple-server port 8001 at regular intervals

[problem.zip](https://github.com/aler9/rtsp-simple-server/files/5749489/problem.zip)

Not sure, but it smells like a timeout problem

**Comment by arkanoid87** [comment] 2020-12-29 04:52
now trying with protocols=4 (tcp) on the rtspclientsink

**Comment by arkanoid87** [comment] 2020-12-29 14:04
9 hours stable with TCP connection between gstreamer and rtsp-simple-server.
So far, so good

**Comment by aler9** [comment] 2021-01-01 18:08
It *could* be that Gstreamer closes the TCP connection after some time, so i have to check this.

**Comment by aler9** [comment] 2021-02-13 10:37
Ok, therefore this is a duplicate of https://github.com/aler9/rtsp-simple-server/issues/149

**Closed by aler9** 2021-02-13 10:37 UTC
Labels: bug
