### ISSUE TITLE
rtsp source ERR: bad status code: 301 (Moved)

### ISSUE THREAD

**Issue by eternally123** [aler9/rtsp-simple-server#150] opened 2020-12-10 02:03 UTC
## Which version are you using?

v0.12.2

## Which operating system are you using?

Linux

## phenomenon
$ ./rtsp-simple-server 
2020/12/10 10:13:01 [0/0/0] rtsp-simple-server v0.12.2
2020/12/10 10:13:01 [0/0/0] [UDP/RTP server] opened on :8000
2020/12/10 10:13:01 [0/0/0] [UDP/RTCP server] opened on :8001
2020/12/10 10:13:01 [0/0/0] [TCP server] opened on :8554
2020/12/10 10:13:01 [0/0/0] [path proxied] rtsp source started
2020/12/10 10:13:01 [0/0/0] [path proxied] connecting to rtsp source
2020/12/10 10:13:01 [0/0/0] [path proxied] rtsp source ERR: bad status code: 301 (Moved)
2020/12/10 10:13:06 [0/0/0] [path proxied] connecting to rtsp source
2020/12/10 10:13:06 [0/0/0] [path proxied] rtsp source ERR: bad status code: 301 (Moved)
2020/12/10 10:13:11 [0/0/0] [path proxied] connecting to rtsp source
2020/12/10 10:13:11 [0/0/0] [path proxied] rtsp source ERR: bad status code: 301 (Moved)
^C

## Question

i want to use RTSP proxy mode,so i modify rtsp-simple-server.yml according to the describe written in README.md. and i want to use it as a proxy, the server is network camer, the client is vlc. so the io stream is vlc --> RTSP proxy model --> network camer.

when i write rtsp-simple-server.yml path such as this:
paths:
  proxied:
    source: rtsp://192.168.8.66:554
it works

but when i write rtsp-simple-server.yml path such as this:
paths:
  proxied:
    source: rtsp://username:password@smedia.mj.sctel.com.cn:9500/DevCode=01207BCBAC2266EEB00/DevAor=01207BCBAC2266EEB00/StreamIndex=0

it doesn't work.(for security, username and password is hidden when i set up this issue)
i wonder maybe the program doesn't has DNS, so i ping smedia.mj.sctel.com.cn and use the actual ip replace the domain name, but it also doesn't work.
(the secode rtsp url is ok ,i can open it in vlc software)

how should i do ? did i write wrong config file?
## guess
the Linux server is in a local area,with an ip 192.168.xxxxxx
but the network camer has a public network ip like 182.145.xxx.xxx
maybe this reason? how should i fix it ?
(addition:) maybe not this reason, i do another lab: use a linux server with a public network ip (aliyun server),but the same problem appears again.

  thanks

**Comment by aler9** [comment] 2020-12-14 11:50
Hello, the server is able to connect to the camera (so it's not a DNS problem), the problem is in the handshake phase between the server and the camera, so it may be a bug in the server.

Please do the following:

The most helpful content you can provide to fix a communication issue between rtsp-simple-server and an external hardware or software, is a dump of the data exchanged between the server and the target (network dump), that can be generated in this way:
1) Download wireshark (https://www.wireshark.org/)
2) Start capturing on the interface used for exchanging RTSP (if the server and the target software are both installed on your pc, the interface is probably "loopback", otherwise it's the one of your network card)
3) Start the server and replicate the issue
4) Stop capturing, save the result in .pcap format
5) Attach

**Comment by aler9** [comment] 2021-03-21 10:32
This can't be fixed without the author's help.

**Closed by aler9** 2021-03-21 10:32 UTC
Labels: bug
