### ISSUE TITLE
For h265 rtsp, HLS [HLS] [muxer test/stream.n3u8] destroyed (no one is publishing to path 'test/stream.n3u8')

### ISSUE THREAD

**Issue by 1021683053** [aler9/rtsp-simple-server#692] opened 2021-11-09 06:07 UTC
error like this https://github.com/aler9/rtsp-simple-server/discussions/468

![image](https://user-images.githubusercontent.com/7711802/140951561-80d0cc86-f608-4533-87ed-ab51c31a9c67.png)

**Comment by aler9** [comment] 2021-11-09 20:00
duplicate of #469

**Closed by aler9** 2021-11-09 20:00 UTC
