### ISSUE TITLE
ERR: unable to parse track 2: unable to get clock rate: invalid rtpmap ()

### ISSUE THREAD

**Issue by aderusha** [aler9/rtsp-simple-server#832] opened 2022-02-12 12:48 UTC
## Which version are you using?

v0.17.16

## Which operating system are you using?

- [ ] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Connection to Samsung camera SNH-P6410BN via RTSP returns the following error:

`ERR: unable to parse track 2: unable to get clock rate: invalid rtpmap ()`

## Describe how to replicate the issue

```yaml
path
  samsung:
    source: rtsp://user:password@10.0.100.50/profile5/media.smp
```

## Did you attach the server logs?

Startup logfile in debug: https://gist.github.com/aderusha/1175e8d7c99d2c8d40d647d9491f8d9b

## Did you attach a network dump?

RTSP SDP decode: https://gist.github.com/aderusha/484fc3d9eff33ed3f2259cae96b7f35c

**Comment by aler9** [comment] 2022-02-13 10:18
Hello, this is an interesting bug; the problem is that the camera wants to publish an application track:

```
m=application 42508 RTP/AVP 107
b=AS:8
```

In order to send and receive RTCP packets, the server needs to know the clock rate of the track.

At the moment i don't know how to obtain the clock rate of that track (application track with payload type 107) and specs aren't clear enough about the matter.

**Comment by aderusha** [comment] 2022-02-14 00:45
How about an option to ignore a track where you can't read the clock rate?

**Comment by 03stevensmi** [comment] 2022-03-14 10:24
i'm having the same issue! is there any help or advice at all on this issue we could do to bypass this problem?

**Comment by aler9** [comment] 2022-03-14 17:29
I did some tests:
* When GStreamer tries to read a RTSP stream with an application track without any codec info, it doesn't setup that specific track; it setups all the others
* When ffmpeg tries to read a RTSP stream with an application track without any codec info, it setups that track but it doesn't generate RTCP receiver reports

**Comment by aler9** [comment] 2022-03-14 17:34
Most cameras with application tracks provides the clock rate, for instance:

```
m=application 0 RTP/AVP 99
c=IN IP4 xxxx
a=control:rtsp://xxxx/defaultPrimary/ana0/trackID=1?rtpPayload=99&streamType=u
a=rtpmap:99 X-avigilon.analytics/90000
```

Here the clock rate is 90000.

Therefore, the server should be adapted to skip tracks that don't provide the clock rate.

**Comment by aler9** [comment] 2022-03-15 11:37
This is fixed in main and will be fixed in the next release.

**Comment by 03stevensmi** [comment] 2022-03-15 19:03
I will do that sometime tomorrow. But in short, I get this exact error message as in this thread. "Err: unable to parse track 2: unable to get clock rate: invalid rtpmap ()" I figured after searching error message that this would be the right place. I will post both logs from both my 2 PC tomorrow.

**Comment by aler9** [comment] 2022-04-10 16:21
added in v0.18.0

**Closed by aler9** 2022-04-10 16:21 UTC
Labels: bug
