### ISSUE TITLE
Error during the microphone stream

### ISSUE THREAD

**Issue by Arcens** [aler9/rtsp-simple-server#113] opened 2020-11-05 17:36 UTC
## Which version are you using?

v0.11.0

## Which operating system are you using?

Windows 

## Describe the problem

Description

Firstly, thank you for this amazing library. I have an error when I add the folowing config in the yml file 
ffmpeg -f dshow  -i audio="Microphone (Realtek Audio)"  -c:a libmp3lame -f rtsp rtsp://localhost:8554/mic, however when i execute this line directly in the power whell when the server is started, is work perfectly. 
`mic:  
    runOnDemand: ffmpeg -f dshow  -i audio="Microphone (Realtek Audio)"  -c:a libmp3lame -f rtsp rtsp://localhost:8554/mic
 `
Bellow the error displayed by the server when I try to execute the stream with VLC

`e780] Could not find audio only device with name ["Microphone] among source devices of type audio.
[dshow @ 000002182a47e780] Searching for audio device within video devices for "Microphone
[dshow @ 000002182a47e780] Could not find audio only device with name ["Microphone] among source devices of type video.
audio="Microphone: I/O error `

Do you have an idea how can I resolve the issue ? 

Thank you for you support.

**Comment by jazzy348** [comment] 2020-11-05 18:05
Hi Arcens,

This looks like an FFMPEG error, not a RTSP server issue. Make sure your DShow device name is correct, you can have FFMPEG search for devices with this command:
ffmpeg -list_devices true -f dshow -i dummy

Kind regards,
Jazzy

**Comment by Arcens** [comment] 2020-11-05 18:09
Hi Jazzy, 
Yes, I have executed this command, and I have the following devices displayed
DirectShow audio devices
[dshow @ 0000020fdfa1dac0]  "Microphone (Realtek Audio)"

And if I try the same command directly in power shell, ffmpeg works perfectly. But If I add the same command in the config yml ffmpeg doesn't work. 

Best regards, 
Arcens

**Comment by Arcens** [comment] 2020-11-05 18:23
Hi Jazzy, 
In order to explain my problem, below the screen shares

1.  Works directly in powershell from Windows

![Works with power shell](https://user-images.githubusercontent.com/20928146/98280819-3e914880-1f9c-11eb-8c83-ce94b81b0381.png)

2.Not works when the command is inside the yml config

![doesntwork](https://user-images.githubusercontent.com/20928146/98280882-57016300-1f9c-11eb-9d22-8121f434c070.png)
 
Best regards, 
Arcens

**Comment by aler9** [comment] 2020-11-07 22:42
Hello, it seems like the server is stripping away the part of the device name in the parenthesis, so "Microphone (Realtek Audio)" becomes "Microphone".
This is caused by a bad implementation of external commands under Windows (https://github.com/aler9/rtsp-simple-server/blob/master/internal/externalcmd/externalcmd.go#L94), and will be fixed ASAP.

**Comment by aler9** [comment] 2020-11-08 22:13
External commands with quotes on Windows are now parsed correctly; the fix will be added to the next release.

**Comment by Arcens** [comment] 2020-11-09 07:39
Hi Aler9, 

Thank you for you support. 
Look forward to the next delivery  :)

Best regards,

**Comment by aler9** [comment] 2020-11-11 10:25
added in v0.12.1

**Closed by aler9** 2020-11-11 10:25 UTC
Labels: bug
