### ISSUE TITLE
RTMP connection closed: DTS is greater than PTS

### ISSUE THREAD

**Issue by tekijiyuu** [aler9/rtsp-simple-server#995] opened 2022-06-18 09:42 UTC
## Which version are you using?

v0.19.1

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

When using OBS with nvenc, with b-frames > 0, get closed connection when try watch stream from rtmp: "closed (DTS is greater than PTS)". 
Correctly working on rtmp without b-frames and working correct on rtsp with and without b-frames.
Also all correctly working on previous version (v0.19.0)
## Describe how to replicate the issue

1. start the server
2. publish with OBS with nvenc and b-frame > 0
3. read with VLC 

## Did you attach the server logs?
2022/06/18 12:22:21 INF [RTMP] [conn 127.0.0.1:5116] opened
2022/06/18 12:22:21 INF [RTMP] [conn 127.0.0.1:5116] is reading from path 'teststream'
2022/06/18 12:22:22 INF [RTMP] [conn 127.0.0.1:5116] closed (DTS is greater than PTS)

 no

## Did you attach a network dump?

 no

**Comment by aler9** [comment] 2022-06-22 16:29
duplicate of #989

**Closed by aler9** 2022-06-22 16:29 UTC
