### ISSUE TITLE
h264_v4l2m2m 

### ISSUE THREAD

**Issue by spookyfirehorse** [aler9/rtsp-simple-server#1283] opened 2022-12-08 12:47 UTC
## Which version are you using?

v0.0.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ x] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue
Hi and Hallo !

sorry for my bad english !!!

computer rpi 4 and rpi 3

boot config

start_x=1
#camera_auto_detect=1

ffmpeg 4.3.5

and thats my script

ffmpeg -hwaccel vulkan -fflags +genpts+nobuffer+igndts+discardcorrupt -hide_banner -strict experimental -async 1
-f alsa -ac 2 -i hw:CARD=S3,DEV=0 -f v4l2 -input_format h264 -use_wallclock_as_timestamps 1 -re -i /dev/video0 -c:v h264_v4l2m2m -b:v 1M -pix_fmt yuv420p
-c:a libopus -b:a 32k -application lowdelay -movflags +faststart+write_colr
-f rtsp -rtsp_transport tcp rtsp://localhost:8557/mystream

the stream is running but when i was looking for that strem with

mpv rtsp://spook:password@lucy:8557/mystream

error massege

[ffmpeg/video] h264: non-existing PPS 0 referenced
[ffmpeg/video] h264: non-existing PPS 0 referenced
[ffmpeg/video] h264: decode_slice_header error
[ffmpeg/video] h264: no frame!

stream is running with ffmpeg 4.3.2

and this day libcamera was updated by raspbian libcamera.so.0.1 to libcamera.so.0.2
so rtsp-simple-server searching for libcamera.so.0.1 error

thank you for your great work

Description

## Describe how to replicate the issue

1. start the server
2. publish with ...
3. read with ...

## Did you attach the server logs?

yes / no

## Did you attach a network dump?

yes / no

**Comment by spookyfirehorse** [comment] 2022-12-19 14:58
[ffmpeg/video] h264: non-existing PPS 0 referenced

**Comment by aler9** [comment] 2023-01-04 22:20
duplicate of #1155

**Closed by aler9** 2023-01-04 22:20 UTC
