### ISSUE TITLE
runOnPublish command not killed after publisher timeout

### ISSUE THREAD

**Issue by softko** [aler9/rtsp-simple-server#595] opened 2021-09-28 14:52 UTC
## Which version are you using?

v0.17.3 in docker

## Which operating system are you using?

OS

- [x] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [x] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

I have runOnPublish which is reading from the path via ffmpeg. When I stop the camera, everything works fine, the process created with runOnPublish is also killed (it's not listed via ps -a). But when the camera is running and I turn off the router, so the camera lost the internet connection, the server log is:
```
[1/1] [RTSPS] [conn REAL_IP:42568] ERR: read tcp 172.28.0.4:8555->REAL_IP:42568: i/o timeout
2021/09/28 16:05:04 I [1/1] [RTSPS] [conn REAL_IP:42568] closed
```
which is as expected, but the process created via runOnPublish is not killed. It's still there with same process id (ps -a). Also API request _/v1/rtspssessions/list_ shows
`{"items":{"627755016":{"remoteAddr":"127.0.0.1:41490","state":"read"}}}`
and API request _/v1/paths/list_ not working - timeout.

Then when the camera is trying to publish again it gets timeouts and session list via API shows
`{"items":{"399376938":{"remoteAddr":"REAL_IP:42744","state":"idle"},"621678548":{"remoteAddr":"REAL_IP:42772","state":"idle"},"627755016":{"remoteAddr":"127.0.0.1:41490","state":"read"},"908996501":{"remoteAddr":"REAL_IP:42750","state":"idle"},"934493558":{"remoteAddr":"REAL_IP:42762","state":"idle"},"940400714":{"remoteAddr":"REAL_IP:42782","state":"idle"}}}`
every publish try ends with new item in state idle.

When I manually kill the process created via runOnPublish, everything is working again - camera is publishing, API paths is responding and sessions shows only 2 items (one publish and one localhost read)

path in yml:
```
source: publisher
sourceProtocol: tcp
runOnPublish: >
  ffmpeg -re -i rtsps://READ_CAM_USER:READ_CAM_PASS@localhost:8555/$RTSP_PATH -c copy -f segment -segment_time 3600 -reset_timestamps 1 -strftime 1 /stream/records/$RTSP_PATH/%Y-%m-%d_%H-%M-%S.mp4
runOnPublishRestart: yes
readUser: READ_CAM_USER
readPass: READ_CAM_PASS
publishIPs: [ALLOWED_FEED_IPS]
```

## Describe how to replicate the issue

Just start the server with runOnPublish command in path, which will be reading from the path (best will be to use the same command as I wrote here). Then start publish to path and simulate losing internet connection on camera side. The runOnPublish command should be still running.

**Comment by aler9** [comment] 2021-09-30 10:48
This is linked to #430 and #495

**Comment by aler9** [comment] 2021-10-03 14:06
The issue is fixed in main and will be fixed in the next release.

**Comment by aler9** [comment] 2021-10-03 14:27
added in v0.17.4

**Closed by aler9** 2021-10-03 14:27 UTC
Labels: bug
