### ISSUE TITLE
RTSP Proxy to FritzBox Cable does not work: ERR: sdp: invalid syntax `c=In IP4 0.0.0.0` (c=In IP4 0.0.0.0)

### ISSUE THREAD

**Issue by ProgiThePro** [aler9/rtsp-simple-server#1119] opened 2022-08-25 13:44 UTC
## Which version are you using?

v0.20.0

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

When I am trying to proxy the RTSP Stream running on my fritzbox 6660 Cable I am getting this error as soon as I am starting the rtsp-simple-server file:

2022/08/25 14:44:17 INF [path proxied] [rtsp source] ERR: sdp: invalid syntax `c=In IP4 0.0.0.0` (c=In IP4 0.0.0.0)

My conf file looks like this:

paths:
  proxied:
    source: rtsp://192.168.177.1:554?/avm=1&freq=602&bw=8&msys=dvbc&mtype=256qam&sr=6900&specinv=1&pids=0,16,17,18,20,1003,130,131

Using VLC to stream the same url works with no Problem.
Using a different IP than my fritzbox's, like my printer's ip leads to a different error message.
Also I tried your deprecated rtsp-simple-proxy and it works but the connection is crashing every 10 seconds.

## Describe how to replicate the issue

1. add the ip of the fritzbox into the source block of any path. Adding query parameters does not change the result.
2. start the rtsp-simple-server
3. watch the error message get posted every 5s or so.

## Did you attach the server logs?

no

## Did you attach a network dump?

yes
[log.zip](https://github.com/aler9/rtsp-simple-server/files/9425209/log.zip)

**Comment by aler9** [comment] 2022-11-03 21:11
Thanks for posting the log, the issue is fixed in v0.20.2.

**Closed by aler9** 2022-11-03 21:11 UTC
Labels: bug
