### ISSUE TITLE
NAT problem(maybe)

### ISSUE THREAD

**Issue by eternally123** [aler9/rtsp-simple-server#147] opened 2020-12-09 03:33 UTC
## Which version are you using?

v0.12.2

## Which operating system are you using?

Linux(ubuntu 18)

## Question

i want to use RTSP proxy mode,so i modify rtsp-simple-server.yml according to the describe written in README.md. and i want to use it as a proxy, the server is network camer, the client is vlc. so the io stream is vlc --> RTSP proxy model --> network camer.

i do two tests:when i run it in host,it works. but when i run it in a virtual machine, it doesn't work,and the error info is :

root @ server102 in ~/src/aler9 [19:20:27] 
$ ./rtsp-simple-server
2020/12/08 19:20:29 [0/0/0] rtsp-simple-server v0.12.2
2020/12/08 19:20:29 [0/0/0] [UDP/RTP server] opened on :8000
2020/12/08 19:20:29 [0/0/0] [UDP/RTCP server] opened on :8001
2020/12/08 19:20:29 [0/0/0] [TCP server] opened on :8554
2020/12/08 19:20:29 [0/0/0] [path proxied] rtsp source started
2020/12/08 19:20:29 [0/0/0] [path proxied] connecting to rtsp source
2020/12/08 19:20:29 [0/0/0] [path proxied] rtsp source ready
2020/12/08 19:20:39 [0/0/0] [path proxied] rtsp source ERR: no packets received recently (maybe there's a firewall/NAT in between)
2020/12/08 19:20:44 [0/0/0] [path proxied] connecting to rtsp source
2020/12/08 19:20:44 [0/0/0] [path proxied] rtsp source ready
2020/12/08 19:20:54 [0/0/0] [path proxied] rtsp source ERR: no packets received recently (maybe there's a firewall/NAT in between)

**Comment by brandousov** [comment] 2020-12-09 05:35
Try to add second `Bridged adapter` (P.M.: Allow All) to your VM (Virtualbox) and find its new external IPv4 with `ip a` command - it working for me. You must to use this new IP for RTSP works fine.

**Comment by iaroshvictor** [comment] 2020-12-09 10:23
removing udp from the config file fixed the issue for me

**Comment by brandousov** [comment] 2020-12-09 21:30
Debian 10, Server v0.12.2 - 

## Config:  
```yml
# For Debugging - my proxied home camera
  test:
    source: record
    sourceProtocol: automatic
    sourceOnDemand: yes
    publishIps: [127.0.0.1,176.15.89.162]

###AUTOGENERATED
###token1
  token1:
    source: rtsp://ff.tj:8554/test
    sourceProtocol: automatic
    sourceOnDemand: yes
    sourceOnDemandStartTimeout: 5s
    sourceOnDemandCloseAfter: 10s
    publishIps: [127.0.0.1]
###end-token1
###token2
  token2:
    source: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov
    sourceProtocol: automatic
    sourceOnDemand: yes
    sourceOnDemandStartTimeout: 5s
    sourceOnDemandCloseAfter: 10s
    publishIps: [127.0.0.1]
###end-token2
###token3
  token3:
    source: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_175k.mov
    sourceOnDemand: yes
    sourceOnDemandStartTimeout: 5s
    sourceOnDemandCloseAfter: 10s
    publishIps: [127.0.0.1]
###end-token3
```

## Log:  
```
2020/12/10 00:19:44 [0/0/0] [client 176.15.89.162:8296] disconnected
2020/12/10 00:19:45 [1/0/0] [client 176.15.89.162:51126] connected
2020/12/10 00:19:45 [1/0/0] [client 176.15.89.162:51126] OPTIONS
2020/12/10 00:19:45 [1/0/0] [client 176.15.89.162:51126] ANNOUNCE
2020/12/10 00:19:45 [1/0/0] [client 176.15.89.162:51126] SETUP
2020/12/10 00:19:45 [1/0/0] [client 176.15.89.162:51126] RECORD
2020/12/10 00:19:45 [1/1/0] [client 176.15.89.162:51126] is publishing to path 'test', 1 track with udp
2020/12/10 00:19:46 [2/1/0] [client 176.15.89.162:8297] connected
2020/12/10 00:19:46 [2/1/0] [client 176.15.89.162:8297] OPTIONS
2020/12/10 00:19:46 [2/1/0] [client 176.15.89.162:8297] DESCRIBE
2020/12/10 00:19:46 [2/1/0] [client 176.15.89.162:8297] ERR: no one is publishing to path 'token1'
2020/12/10 00:19:46 [1/1/0] [client 176.15.89.162:8297] disconnected
2020/12/10 00:19:46 [2/1/0] [client 176.15.89.162:8298] connected
2020/12/10 00:19:46 [2/1/0] [client 176.15.89.162:8298] SETUP
2020/12/10 00:19:46 [2/1/0] [client 176.15.89.162:8298] ERR: unable to find control attribute (rtsp://ff.tj:8554/token1)
2020/12/10 00:19:46 [1/1/0] [client 176.15.89.162:8298] disconnected
```
- it working only when I made `systemctl restart rtsp-simple-server && systemctl status rtsp-simple-server`, config hot-reload stops all streams untill I restart the server itself.  

- I have also problem with error `rtsp source ERR: no packets received recently (maybe there's a firewall/NAT in between)` for token2 and token3 from my configs, but my home camera, proxied to the internet with ffmpeg from local VM works fine!

**Comment by aler9** [comment] 2020-12-31 19:54
> but if you edit it with Notepad++ with WinSCP it returns error ERR: EOF and stop all your streams.

let's start with that, i'm checking

**Comment by aler9** [comment] 2021-01-01 17:35
Hello,

1. Please report each problem in a separate issue, otherwise it's very difficult to isolate them, replicate them and solve them

2. 

> but if you edit it with Notepad++ with WinSCP it returns error ERR: EOF and stop all your streams.

Hot reloading by monitoring changes in the configuration file was conceived because it's the only way to make it work on both Linux, Windows and Mac OS X. The problem is that the configuration file must be written instantly - it can't be resetted and, after a while, filled. In case of a remote machine, accessed with FTP or similar, my advice is to save any new version of the configuration file to another file (for instance, rtsp-simple-server.yml2) and then move it to the original position (rtsp-simple-server.yml)

3. rtsp source ERR: no packets received recently (maybe there's a firewall/NAT in between)

**Comment by aler9** [comment] 2021-01-01 17:46
Hello,

1.

Please report each problem in a separate issue, otherwise it's very difficult to isolate them, replicate them and solve them

2. 

 > but if you edit it with Notepad++ with WinSCP it returns error ERR: EOF and stop all your streams.

Hot reloading by monitoring changes in the configuration file was conceived because it's the only way to make it work on both Linux, Windows and Mac OS X. The problem is that the configuration file must be written instantly - it can't be resetted and, after a while, filled. In case of a remote machine, accessed with FTP or similar, my advice is to save any new version of the configuration file to another file (for instance, rtsp-simple-server.yml2) and then move it to the original position (rtsp-simple-server.yml)

3.

> rtsp source ERR: no packets received recently (maybe there's a firewall/NAT in between)

Unfortunately UDP works only when there isn't a NAT between the server and the client - the reason of VLC and ffmpeg being able to play the stream is that they first try with UDP, then they wait for some seconds, and if they don't receive any packet they try again with UDP. Maybe i can replicate this behavior in the server.

4.

> it working only when I made systemctl restart rtsp-simple-server && systemctl status rtsp-simple-server, config hot-reload stops all streams untill I restart the server itself.

It may be related to #130, but i'm still unable to replicate it (i installed the server inside a virtualbox-base VM with Debian 10). Please provide:
* the original configuration
* the new configuration
* how you triggered the change (how the configuration got updated? manually with an editor?)

**Comment by brandousov** [comment] 2021-01-02 02:44
All problems solved - all of them was caused by WinSCP remote yml editing with Notepad++.  
Sorry, I forget to close this issue!

**Closed** 2021-01-20 21:06 UTC
Labels: bug

**Comment by tuncch1907003** [comment] 2021-02-03 07:21
Hello ! I also have err the same ! 

I used Centos7 operating system to do this project. However, when I run it on my computer everything is fine, but when running on Centos 7 and Ip public this error occurred. I have turned off all firewall for this device. I have a problem when a remote machine publishes an input stream.
![image](https://user-images.githubusercontent.com/64294295/106712116-16f95d00-662b-11eb-83d6-913f9a23fe97.png)

**Comment by iaroshvictor** [comment] 2021-02-03 10:46
> Hello ! I also have err the same !
> 
> I used Centos7 operating system to do this project. However, when I run it on my computer everything is fine, but when running on Centos 7 and Ip public this error occurred. I have turned off all firewall for this device. I have a problem when a remote machine publishes an input stream. I have already configed sourceProtocol: tcp
> 
> ![image](https://user-images.githubusercontent.com/64294295/106713952-bd466200-662d-11eb-8674-ff808294c23c.png)
> 
> ![image](https://user-images.githubusercontent.com/64294295/106712116-16f95d00-662b-11eb-83d6-913f9a23fe97.png)

That's the exact issue i had on CentOS 8. I solved it by removing udp from protocols in the config file

**Comment by tuncch1907003** [comment] 2021-02-04 02:07
> > Hello ! I also have err the same !
> > I used Centos7 operating system to do this project. However, when I run it on my computer everything is fine, but when running on Centos 7 and Ip public this error occurred. I have turned off all firewall for this device. I have a problem when a remote machine publishes an input stream. I have already configed sourceProtocol: tcp
> > ![image](https://user-images.githubusercontent.com/64294295/106713952-bd466200-662d-11eb-8674-ff808294c23c.png)
> > ![image](https://user-images.githubusercontent.com/64294295/106712116-16f95d00-662b-11eb-83d6-913f9a23fe97.png)
> 
> That's the exact issue i had on CentOS 8. I solved it by removing udp from protocols in the config file rtsp-simple-server.yml (line 17)

If I remove UDP then the audio stream is really slow, and I don't want that. Can you explain and fix this ?? Is this an error?

**Comment by tuncch1907003** [comment] 2021-02-06 04:04
Help me ! I have configure PUBLISHUSER and PUBLISHPASS it is wrong ! 

![image](https://user-images.githubusercontent.com/64294295/107108491-e43da780-686a-11eb-8a1e-787fdcd6d9a9.png)
