### ISSUE TITLE
Enhancement: Allow wildcard paths and reference to path in runOn* calls

### ISSUE THREAD

**Issue by xieliwei** [aler9/rtsp-simple-server#51] opened 2020-08-02 16:19 UTC
If I have ondemand rooms for a conference streaming server, it will be nice if the path can be used as a parameter for the runOnDemand call, which will call a helper script that redirects the correct stream to the server.

For example, the config script may look like this:

paths:
  conf*:
    source: record
    sourceProtocol: udp
    runOnDemand: redirectStream.sh $1

So a client connecting via rtsp://example.com/conf1234
Will spawn redirectStream.sh 1234, which redirects the necessary rtsp stream over to the server.

Alternatively, the path can be passed as an environment variable to the script, if trying to parse the parameter identifier might be troublesome.

I'm a beginner at Go, but will try implementing a patch to do this over the week. Opening this issue in case others are potentially working on this.

**Comment by aler9** [comment] 2020-08-02 17:00
Hi, this is a duplicate of #47, of course a patch would be very welcomed.

**Closed by aler9** 2020-08-02 17:00 UTC
