### ISSUE TITLE
Unable to proxy rtsps stream from UniFi Dream Machine Pro

### ISSUE THREAD

**Issue by StFS** [aler9/rtsp-simple-server#797] opened 2022-01-29 02:13 UTC
Hi there.

I'm trying to use rtsp-simple-server to proxy an rtsps stream from my UniFi Protect camera over to an rtsp (no encryption) stream. The reason is that I use a smarthome hub (Hubitat) where I want to create a dashboard where I can preview the cameras but that dashboard does not support rtsps streams.

I've configured rtsp-simple-server with the following paths config:

```
paths:
  garage:
    source: rtsps://192.168.1.1:7441/SomErANDomStrinG?enableSrtp
    sourceFingerprint: <MY_UDMP_CERT_FINGERPRINT>
```

But when I run rtsp-simple-server I keep getting messages stating `payload size greater than maximum allowed`:

```
2022/01/29 01:59:00 INF rtsp-simple-server v0.17.14
2022/01/29 01:59:00 INF [path garage] [rtsp source] started
2022/01/29 01:59:00 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2022/01/29 01:59:00 INF [API] listener opened on 127.0.0.1:9997
2022/01/29 01:59:00 INF [path garage] [rtsp source] ready
2022/01/29 01:59:00 INF [path garage] [rtsp source] ERR: payload size greater than maximum allowed (5213 vs 4096)
2022/01/29 01:59:05 INF [path garage] [rtsp source] ready
2022/01/29 01:59:06 INF [path garage] [rtsp source] ERR: payload size greater than maximum allowed (4126 vs 4096)
2022/01/29 01:59:11 INF [path garage] [rtsp source] ready
2022/01/29 01:59:11 INF [path garage] [rtsp source] ERR: payload size greater than maximum allowed (64245 vs 4096)
2022/01/29 01:59:16 INF [path garage] [rtsp source] ready
2022/01/29 01:59:16 INF [path garage] [rtsp source] ERR: payload size greater than maximum allowed (5385 vs 4096)
2022/01/29 01:59:21 INF [path garage] [rtsp source] ready
2022/01/29 01:59:22 INF [path garage] [rtsp source] ERR: payload size greater than maximum allowed (4460 vs 4096)
2022/01/29 01:59:27 INF [path garage] [rtsp source] ready
2022/01/29 01:59:27 INF [path garage] [rtsp source] ERR: payload size greater than maximum allowed (63733 vs 4096)
^C2022/01/29 01:59:27 INF shutting down gracefully
2022/01/29 01:59:27 INF [path garage] [rtsp source] stopped
2022/01/29 01:59:27 INF [API] listener is closing
2022/01/29 01:59:27 INF [RTSP] listener is closing
2022/01/29 01:59:27 INF waiting for external commands
```

As you can see I've tried to bump the buffer size from the default 2048 to 4096 but that doesn't work. The numbers I'm seeing in the logs seem to indicate that I'd need a buffer of 64Kb to _maybe_ avoid this but given that the default is 2048 and the comment there says that I shouldn't be touching it it seems unlikely that it should be set to that size. However, for the fun of it I tried doing that and the errors on the rtsp-simple-server side do in fact stop appearing and the stream seems to be "stable" but if I try to connect to it using VLC I get a tsunami of error messages in the VLC log but only a message stating that a session is reading from the "garage" stream on the rtsp-simple-server side. For a long while nothing is displayed in VLC but after waiting I eventually did see that VLC showed a video window (it even looked like it might be the correct size) but no video was displayed (just a black screen) and the errors in VLC continued:

```
$ vlc rtsp://localhost:8554/garage

VLC media player 3.0.16 Vetinari (revision 3.0.16-0-g5e70837d8d)
[00007f9ee6504340] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
2022-01-29 02:05:27.671 VLC[70866:3569177] Can't find app with identifier com.apple.iTunes
[00007f9ee6577270] videotoolbox decoder: Using Video Toolbox to decode 'h264'
[00007f9ee633d4a0] main decoder error: buffer deadlock prevented
[00007f9ee6577270] main decoder error: buffer deadlock prevented
2022-01-29 02:05:28.800 VLC[70866:3569177] Can't find app with identifier com.apple.iTunes
[h264 @ 0x7f9ee884d000] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee884d000] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee884d000] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee884d000] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee884d000] no frame!
[h264 @ 0x7f9ee884d000] Invalid NAL unit 8, skipping.
[h264 @ 0x7f9ee884d000] Invalid NAL unit 8, skipping.
[h264 @ 0x7f9ee884d000] no frame!
[h264 @ 0x7f9eea810c00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9eea810c00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9eea810c00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9eea810c00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9eea810c00] no frame!
[h264 @ 0x7f9ee884d000] Invalid NAL unit 8, skipping.
[h264 @ 0x7f9ee884d000] Invalid NAL unit 8, skipping.
[h264 @ 0x7f9ee884d000] slice type 22 too large at 2
[h264 @ 0x7f9ee884d000] decode_slice_header error
[h264 @ 0x7f9ee884d000] no frame!
[h264 @ 0x7f9ee884d000] illegal modification_of_pic_nums_idc 32
[h264 @ 0x7f9ee884d000] decode_slice_header error
[h264 @ 0x7f9ee884d000] no frame!
[h264 @ 0x7f9ee781fa00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee781fa00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee781fa00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee781fa00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee781fa00] reference overflow (pps)
[h264 @ 0x7f9ee781fa00] no frame!
[h264 @ 0x7f9ee781fa00] Invalid NAL unit 8, skipping.
[h264 @ 0x7f9ee781fa00] Invalid NAL unit 8, skipping.
[h264 @ 0x7f9ee781fa00] no frame!
[h264 @ 0x7f9ee7858a00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee781fa00] Invalid NAL unit 17, skipping.
[h264 @ 0x7f9ee781fa00] Invalid NAL unit 17, skipping.
[h264 @ 0x7f9ee781fa00] Invalid NAL unit 17, skipping.
[h264 @ 0x7f9ee781fa00] reference overflow (pps)
[h264 @ 0x7f9ee781fa00] no frame!
[h264 @ 0x7f9ee7858a00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee7858a00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee7858a00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee7858a00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee7858a00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee7858a00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee7858a00] reference overflow (pps)
[h264 @ 0x7f9ee7858a00] illegal modification_of_pic_nums_idc 5
[h264 @ 0x7f9ee7858a00] decode_slice_header error
[h264 @ 0x7f9ee7858a00] no frame!
[h264 @ 0x7f9ee781fa00] Invalid NAL unit 16, skipping.
[h264 @ 0x7f9ee781fa00] Invalid NAL unit 15, skipping.
[h264 @ 0x7f9ee781fa00] Invalid NAL unit 15, skipping.
[h264 @ 0x7f9ee781fa00] Invalid NAL unit 15, skipping.
[h264 @ 0x7f9ee781fa00] Invalid NAL unit 3, skipping.
[h264 @ 0x7f9ee781fa00] illegal aspect ratio
[h264 @ 0x7f9ee781fa00] illegal aspect ratio
[h264 @ 0x7f9ee781fa00] illegal aspect ratio
[h264 @ 0x7f9ee781fa00] reference overflow (pps)
[h264 @ 0x7f9ee781fa00] no frame!
[h264 @ 0x7f9ee6934e00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee6934e00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee6934e00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee6934e00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee6934e00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee6934e00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee6934e00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee6934e00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee6934e00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee6934e00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee6934e00] illegal aspect ratio
[h264 @ 0x7f9ee6934e00] illegal aspect ratio
[h264 @ 0x7f9ee6934e00] illegal aspect ratio
[h264 @ 0x7f9ee6934e00] SEI type 205 size 752 truncated at 670
[h264 @ 0x7f9ee6934e00] no frame!
[h264 @ 0x7f9ee6934e00] Invalid NAL unit 7, skipping.
[h264 @ 0x7f9ee6934e00] Invalid NAL unit 7, skipping.
[h264 @ 0x7f9ee6934e00] Invalid NAL unit 7, skipping.
[h264 @ 0x7f9ee6934e00] no frame!
[h264 @ 0x7f9ee682d600] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee682d600] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee682d600] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee682d600] illegal aspect ratio
[h264 @ 0x7f9ee682d600] illegal aspect ratio
[h264 @ 0x7f9ee682d600] illegal aspect ratio
[h264 @ 0x7f9ee682d600] reference overflow (pps)
[h264 @ 0x7f9ee682d600] FMO not supported
[h264 @ 0x7f9ee682d600] slice type 22 too large at 2
[h264 @ 0x7f9ee682d600] decode_slice_header error
[h264 @ 0x7f9ee682d600] no frame!
[h264 @ 0x7f9ee6934e00] no frame!
[h264 @ 0x7f9ee682d600] Invalid NAL unit 7, skipping.
[h264 @ 0x7f9ee682d600] no frame!
[h264 @ 0x7f9ee6866800] no frame!
[h264 @ 0x7f9ee687ae00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee687ae00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee687ae00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee687ae00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee687ae00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee687ae00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee687ae00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee687ae00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee687ae00] illegal aspect ratio
[h264 @ 0x7f9ee687ae00] illegal aspect ratio
[h264 @ 0x7f9ee687ae00] illegal aspect ratio
[h264 @ 0x7f9ee687ae00] no frame!
[h264 @ 0x7f9ee6934e00] Invalid NAL unit 4, skipping.
[h264 @ 0x7f9ee6934e00] no frame!
[h264 @ 0x7f9ee7956200] illegal aspect ratio
[h264 @ 0x7f9ee7956200] illegal aspect ratio
[h264 @ 0x7f9ee7956200] illegal aspect ratio
[h264 @ 0x7f9ee7956200] illegal aspect ratio
[h264 @ 0x7f9ee7956200] illegal aspect ratio
[h264 @ 0x7f9ee7956200] illegal aspect ratio
[h264 @ 0x7f9ee7956200] FMO not supported
[h264 @ 0x7f9ee7956200] no frame!
[h264 @ 0x7f9ee7975e00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee7975e00] no frame!
[h264 @ 0x7f9ee7923c00] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee7923c00] no frame!
[h264 @ 0x7f9ee89ce200] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee89ce200] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee89ce200] Invalid NAL unit 0, skipping.
[h264 @ 0x7f9ee89ce200] illegal aspect ratio
[h264 @ 0x7f9ee89ce200] illegal aspect ratio
[h264 @ 0x7f9ee89ce200] illegal aspect ratio
[h264 @ 0x7f9ee89ce200] illegal aspect ratio
[h264 @ 0x7f9ee89ce200] illegal aspect ratio
[h264 @ 0x7f9ee89ce200] illegal aspect ratio
[h264 @ 0x7f9ee89ce200] SEI type 111 size 824 truncated at 815
[h264 @ 0x7f9ee89ce200] no frame!
[...snip...]
```

I'm pretty lost here and suspect that the problem might possibly be on the UniFi side, but I wanted to ask here before giving up on this.

**Comment by aler9** [comment] 2022-01-29 19:20
Hello,

> the comment there says that I shouldn't be touching it it seems unlikely that it should be set to that siz

The comment says

> this shouldn't be touched unless the server reports errors about the buffer size.

Since the server is reporting errors about the buffer size, you should increase the parameter.

This error is caused by a bad implementation of the RTP protocol by the UniFi camera: H264 units should be splitted into RTP packets with a size not higher than 1500 bytes. The RTP protocol allows to split H264 units of arbitrary size into multiple packets. Your UniFi camera, instead, puts an entire H264 unit into a single RTP packet. This doesn't allow to route the packet with the UDP transport protocol, that requires that all packets have a size less than 1500 bytes (that is the UDP MTU).

**Comment by aler9** [comment] 2022-05-04 07:45
This is probably fixed with v0.18.0, since the server now remuxes oversized RTP packets into smaller ones. Open another issue if you still have problems.

**Closed by aler9** 2022-05-04 07:45 UTC
Labels: question

**Comment by StFS** [comment] 2022-05-04 09:04
Thank you! I will give this a go again then when I get the chance.

**Comment by tbnguyen1407** [comment] 2022-08-19 06:07
Hello,

Problem seems to be back in v0.20.0

```
2022/08/19 13:43:27 INF [path 339671ba828f31458ace139c1ea73af5] [rtsp source] ERR: payload size (32793) greater than maximum allowed (1472)
```

We are pulling using TCP. I think if there is a size check it should only applies to UDP.

**Comment by aler9** [comment] 2022-08-27 15:48
> We are pulling using TCP. I think if there is a size check it should only applies to UDP.

The question isn't related to a comformity check. Supporting RTP packets with arbitrary sizes have two implication:

* In order to receive such packets, the server must allocate buffers big enough to hold these packets, greatly increasing RAM consumption
* These packets can't be routed to UDP clients
