### ISSUE TITLE
ERR: data is too big

### ISSUE THREAD

**Issue by BoBXygene** [aler9/rtsp-simple-server#339] opened 2021-04-05 02:00 UTC
Intermittent black video output with "ERR: data is too big" in the console.

v0.15.1

windows 10 pro x64 build 21327 prerelease (to have the gpu selector)

As time goes, this get more and more frequent until OBS says the remote end not responds and i get complete black output with the video client.

streaming source from OBS x264 via rtmp 1080p 60fps CQP10 video.

Even if i push the quantizer, to lower bitrate and quality, it still does this error.

The streaming network is a direct attached 2.5G couple of dedicated ethernet interfaces, peaks about 1.5 gbits/s from time to time.
(when i transfer files it runs flawless at ~300Mo/s)

Dunno which is culprit, this software or OBS.

**Comment by aler9** [comment] 2021-04-05 07:21
hello, this is a duplicate of #206 and fixed in v0.15.2

**Closed by aler9** 2021-04-05 07:21 UTC
