### ISSUE TITLE
Could server hls and ll-hls at the same time?

### ISSUE THREAD

**Issue by lystormenvoy** [aler9/rtsp-simple-server#1453] opened 2023-02-07 05:43 UTC
## Describe the feature

We need provide HLS stream and LL-HLS stream at the same time for difference clients.
And HLS segments save in file system then we can server it via nginx.

**Comment by aler9** [comment] 2023-02-07 08:14
This is a duplicate of #1322 and #967 . Please use the search tool before opening a new issue.

**Closed** 2023-02-07 08:14 UTC
