### ISSUE TITLE
invalid memory address or nil pointer dereference at ringbuffer.go:32

### ISSUE THREAD

**Issue by eLvErDe** [aler9/rtsp-simple-server#792] opened 2022-01-27 08:31 UTC
## Which version are you using?

v0.17.11

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

```
rtsp-simple-server[720918]: panic: runtime error: invalid memory address or nil pointer dereference
rtsp-simple-server[720918]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x87e8f6]
rtsp-simple-server[720918]: goroutine 9751 [running]:
rtsp-simple-server[720918]: github.com/aler9/gortsplib/pkg/ringbuffer.(*RingBuffer).Close(...)
rtsp-simple-server[720918]: #011/go/pkg/mod/github.com/aler9/gortsplib@v0.0.0-20211208171701-d7e1c7c8d351/pkg/ringbuffer/ringbuffer.go:32
rtsp-simple-server[720918]: github.com/aler9/gortsplib.(*Client).playRecordStop(0xc001efb200, 0x1)
rtsp-simple-server[720918]: #011/go/pkg/mod/github.com/aler9/gortsplib@v0.0.0-20211208171701-d7e1c7c8d351/client.go:818 +0x196
rtsp-simple-server[720918]: github.com/aler9/gortsplib.(*Client).doClose(0xc001efb200, 0x8b)
rtsp-simple-server[720918]: #011/go/pkg/mod/github.com/aler9/gortsplib@v0.0.0-20211208171701-d7e1c7c8d351/client.go:595 +0x227
rtsp-simple-server[720918]: github.com/aler9/gortsplib.(*Client).run(0xc001efb200)
rtsp-simple-server[720918]: #011/go/pkg/mod/github.com/aler9/gortsplib@v0.0.0-20211208171701-d7e1c7c8d351/client.go:582 +0xaa
rtsp-simple-server[720918]: created by github.com/aler9/gortsplib.(*Client).Start
rtsp-simple-server[720918]: #011/go/pkg/mod/github.com/aler9/gortsplib@v0.0.0-20211208171701-d7e1c7c8d351/client.go:318 +0x5b5
```

It started happening somewhere between 0.15.5 and 0.17.11, never reported by my users before.

In the meantime, I'll deploy 0.17.14 + RTSP header fix because I'm also interested in #702 and will give a feedback here.

Description

## Describe how to replicate the issue

Sadly I don't know how to replicate this but it's happening to use on bi-weekly basis so I can easily test a patch and report next week if it fixed the issue or not !

## Did you attach the server logs?

No but traceback is attached, I don't think logs are relevant here.

## Did you attach a network dump?

No but traceback is attached, I don't think logs are relevant here.

Thanks in advance !

**Comment by aler9** [comment] 2022-01-27 23:40
Hello, are you sure that this happens with the latest version too? Furthermore, since some versions there's a memory leak that has been [recently fixed](ef255af0933d54b9ffeb65e94d69e25deee925ba) - this may be the cause of the nil pointer, that may be caused by memory exhaustion. This fix will be published in v0.17.15.

**Comment by eLvErDe** [comment] 2022-01-28 08:17
Hi, not yet sure, I just upgraded yesterday, I'll close it myself it's not happening anymore by the end of next week

**Comment by eLvErDe** [comment] 2022-01-31 09:05
It happen with the 17.13 release patched from #702

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x87f1b6]
goroutine 15640 [running]:
github.com/aler9/gortsplib/pkg/ringbuffer.(*RingBuffer).Close(...)
#011/go/pkg/mod/github.com/aler9/gortsplib@v0.0.0-20220119221137-eb224164ca12/pkg/ringbuffer/ringbuffer.go:32
github.com/aler9/gortsplib.(*Client).playRecordStop(0xc019a80900, 0x1)
#011/go/pkg/mod/github.com/aler9/gortsplib@v0.0.0-20220119221137-eb224164ca12/client.go:825 +0x196
github.com/aler9/gortsplib.(*Client).doClose(0xc019a80900, 0x0)
#011/go/pkg/mod/github.com/aler9/gortsplib@v0.0.0-20220119221137-eb224164ca12/client.go:596 +0x227
github.com/aler9/gortsplib.(*Client).run(0xc019a80900)
#011/go/pkg/mod/github.com/aler9/gortsplib@v0.0.0-20220119221137-eb224164ca12/client.go:583 +0xaa
created by github.com/aler9/gortsplib.(*Client).Start
#011/go/pkg/mod/github.com/aler9/gortsplib@v0.0.0-20220119221137-eb224164ca12/client.go:319 +0x5b5
2022/01/31 06:01:53 INF rtsp-simple-server v0.17.13-8-g50144d6
```

**Comment by aler9** [comment] 2022-01-31 09:31
Please try again with v0.17.15 since there's https://github.com/aler9/gortsplib/commit/9603037fb337be21cf5349c77edc652ac2c3957d

**Comment by aler9** [comment] 2023-02-04 15:55
This has been opened for over a year and there are no recent sights of the crash, therefore i'm closing the issue.

**Closed by aler9** 2023-02-04 15:55 UTC
Labels: bug
