### ISSUE TITLE
Crash on startup on Raspbian Buster with v0.9.14 precompiled binary

### ISSUE THREAD

**Issue by fragger42** [aler9/rtsp-simple-server#86] opened 2020-09-21 20:48 UTC
## Which version are you using?

v0.9.14

## Which operating system are you using?

Raspbian Buster

## Describe the problem

The precompiled binaries always crash. I've downloaded the version for ArmV7 (rtsp-simple-server_v0.9.14_linux_arm7.tar.gz) and it crashes with a panic. The older v0.9.13 runs fine. The v0.9.14 crashes with my own config as well as a the one that is provided in the tar.gz archive.

> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x12298]
> 
> goroutine 1 [running]:
> main.(*program).log(0x2066400, 0x4713a8, 0x15, 0x208df4c, 0x1, 0x1)
>         /s/main.go:143 +0x24
> main.newProgram(0x2110018, 0x1, 0x1, 0x512c90, 0x21020d0, 0x47a64, 0x2100030, 0x0)
>         /s/main.go:97 +0x6d4
> main.main()
>         /s/main.go:380 +0x6c

The "--help" command works but as soon as you try to really launch the program it crashes.

**Comment by aler9** [comment] 2020-09-22 06:45
Hello, thanks for reporting the issue, this was caused by a [bug in Go](https://github.com/golang/go/issues/9959) that causes a crash when the functions of the `atomic` package are called on members of structs that are not 64bit-aligned.
Go does not provide a way to align structs (while C does), and neither report the issue during compilation.

**Comment by aler9** [comment] 2020-09-22 06:46
Fixed in v0.9.15

**Closed** 2020-09-22 06:56 UTC
Labels: bug

**Comment by fragger42** [comment] 2020-09-22 08:17
Works fine, thanks for the quick fix and your work on this fantastic tool!
