### ISSUE TITLE
invalid memory address or nil pointer dereference at clientman.go:90

### ISSUE THREAD

**Issue by eLvErDe** [aler9/rtsp-simple-server#217] opened 2021-02-22 07:25 UTC
## Which version are you using?

v0.14.0 (can try with 0.14.1 but I see no change related)

## Which operating system are you using?

OS

- [X] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [X] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

Hello,

We just encountered a segmentation fault in RTSP porxy than happened four times in a row and seems to be gone now so I suspect a transitional network issue that lead to unhandled state in code and is gone now.

Here is the complete stack trace:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x8196cd]
goroutine 900 [running]:
github.com/aler9/gortsplib.(*ServerConn).NetConn(...)
        /go/pkg/mod/github.com/aler9/gortsplib@v0.0.0-20210129115125-ec3002e995d9/serverconn.go:242
github.com/aler9/rtsp-simple-server/internal/clientrtsp.(*Client).log(0xc000de29a0, 0x1, 0x965a06, 0xe, 0xc001118d30, 0x1, 0x1)
        /s/internal/clientrtsp/client.go:143 +0x2d
github.com/aler9/rtsp-simple-server/internal/clientrtsp.New(0xc001118e00, 0x216a, 0x2540be400, 0x0, 0x0, 0x0, 0xc0001166f0, 0xc00019e118, 0xc00011e200, 0x0, ...)
        /s/internal/clientrtsp/client.go:117 +0x1ae
github.com/aler9/rtsp-simple-server/internal/clientman.(*ClientManager).run(0xc00019e0a0)
        /s/internal/clientman/clientman.go:134 +0x769
created by github.com/aler9/rtsp-simple-server/internal/clientman.New
        /s/internal/clientman/clientman.go:90 +0x1c6
```

## Describe how to replicate the issue

Sadly the problem is gone now but that would be great if it could never happen again :D

Let me know if there's something we can do to help if such situation occurs, like getting some better stack dump or something, I'm not a golang expert, maybe that one is enough to add an extra try/catch :)

Thanks in advance,

Best regards, Adam.

**Comment by eLvErDe** [comment] 2021-02-22 08:23
Okay, quite a good news here:

Imho, the issue is from RTSP consumer side, not publisher side. We identified some specific workflow happening this monring and we have been able to trigger the same crash on staging environment.
It basically involve attaching and releasing quite a massive amount of onDemand streams.

So the good news is that we should be able to provide a network trace if it can help (but I'm not sure it would be helpful as it will contains dozens of different streams) but also, that we can rebuild / test any patch you may need to test (e.g: adding some context log before the crash) :-)

Regards, Adam.

**Comment by aler9** [comment] 2021-03-04 18:06
Hello, this is a duplicate of https://github.com/aler9/rtsp-simple-server/issues/193, anyway i think i should try to fix the issue once for all.

**Closed by aler9** 2021-03-04 18:06 UTC

**Comment by eLvErDe** [comment] 2021-03-04 18:14
Agreed, btw I sent you an email, got it ?
