### ISSUE TITLE
RTSP Proxy: Start from keyframe

### ISSUE THREAD

**Issue by ethaniel** [aler9/rtsp-simple-server#1299] opened 2022-12-12 17:48 UTC
## Describe the feature

Thank you for your amazing solution. I wanted to request a small feature - is it possible to keep the last keyframe of a RTSP stream in memory, so when clients connect to the proxy, they would receive this last keyframe first? 

if I understand correctly, right now clients starts receiving streams from the moment they connect (which is most likely to be a non-keyframe), resulting in a weird image:

![image](https://user-images.githubusercontent.com/941973/207118226-5099b2a9-bf9e-4874-9ede-d68a3796c28f.png)

If we prepended the client's stream with a cached keyframe, the picture would be much much nicer till a proper keyframe arrives.

Just to be clear - I'm advocating for keeping a rolling storage of keyframes only (as a new keyframe arrives, the old one gets deleted from memory).

**Comment by aler9** [comment] 2022-12-12 18:05
Hello, this is a duplicate of #1209 - it's a feature that is planned.

**Closed by aler9** 2022-12-12 18:05 UTC
