### ISSUE TITLE
v0.8.5 using TCP results in  i/o timeout and re-connect after a minute

### ISSUE THREAD

**Issue by gustavobsch** [aler9/rtsp-simple-server#29] opened 2020-07-09 22:08 UTC
I'm running v0.8.5 connecting to v4l2rtspserver cameras. I observe persistent timeouts and re-connects every minute when using TCP. Using UDP works fine. 

protocols: [udp, tcp]
rtspPort: 8554
rtpPort: 8000
rtcpPort: 8001
readTimeout: 5s
writeTimeout: 5s
preScript:
postScript:
pprof: false
paths:
  all:
    source: record
    sourceProtocol: udp
    publishUser:
    publishPass:
    publishIps: []
    readUser:
    readPass:
    readIps: []
  cam10:
    source: rtsp://192.168.14.87:8554/unicast
    sourceProtocol: tcp

2020/07/09 21:59:07 [1/0/1] [client 192.168.14.87:40482] ERR: read tcp 172.16.6.16:8554->192.168.14.87:40482: use of closed network connection
2020/07/09 21:59:07 [0/0/0] [client 192.168.14.87:40482] disconnected
2020/07/09 21:59:12 [0/0/0] [streamer cam10] initializing with protocol tcp
2020/07/09 21:59:12 [0/1/0] [streamer cam10] ready

2020/07/09 22:00:22 [0/1/0] [streamer cam10] ERR: read tcp 172.16.6.16:48158->192.168.14.99:8554: i/o timeout
2020/07/09 22:00:22 [0/0/0] [streamer cam10] not ready
2020/07/09 22:00:27 [0/0/0] [streamer cam10] initializing with protocol tcp
2020/07/09 22:00:27 [0/1/0] [streamer cam10] ready

2020/07/09 22:01:37 [0/1/0] [streamer cam10] ERR: read tcp 172.16.6.16:48686->192.168.14.99:8554: i/o timeout
2020/07/09 22:01:37 [0/0/0] [streamer cam10] not ready
2020/07/09 22:01:42 [0/0/0] [streamer cam10] initializing with protocol tcp
2020/07/09 22:01:42 [0/1/0] [streamer cam10] ready

2020/07/09 22:02:52 [0/1/0] [streamer cam10] ERR: read tcp 172.16.6.16:49214->192.168.14.99:8554: i/o timeout
2020/07/09 22:02:52 [0/0/0] [streamer cam10] not ready
2020/07/09 22:02:57 [0/0/0] [streamer cam10] initializing with protocol tcp
2020/07/09 22:02:57 [0/1/0] [streamer cam10] ready

**Comment by aler9** [comment] 2020-07-10 06:16
duplicate of https://github.com/aler9/rtsp-simple-server/issues/22, this is caused by the lack of a RTCP implementation, i'm working to fix it.

**Closed by aler9** 2020-07-10 06:16 UTC

**Comment by aler9** [comment] 2020-07-12 10:35
This is fixed in v0.8.7
