### ISSUE TITLE
Could not write header for output file #0 (incorrect codec parameters ?): Server returned 400 Bad Request Error initializing output stream 0:2 --

### ISSUE THREAD

**Issue by wazerstar** [aler9/rtsp-simple-server#901] opened 2022-03-26 21:14 UTC
## Which version are you using?

v0.17.17

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I want to integrate subtitles that comes in teletext format and works fine when I add sample.mp4 to the end instead of -f rtsp rtsp://127.0.0.1:$RTSP_PORT/$RTSP_PATH

## Describe how to replicate the issue

I simply add the ffmpeg cmd to rstp-simple-server and run the server ip via vlc.

If a test streams is needed to test with I can provide a link but want it to be secured so nobody else can see it.

After some googling I found out that you could add live.stream: below path: but did not do anything in this case.

Command
```
paths:
  live.stream:
  c1:
   runOnDemand: ffmpeg -txt_format text -txt_page 693 -fix_sub_duration -i http://IP:PORT -map 0:v -c:v copy -map 0:1 -c:a copy -map 0:2 -c:s:0 mov_text -metadata:s:s language=dan -drop_pkts_on_overflow 1 -attempt_recovery 1 -recovery_wait_time 1 -f rtsp rtsp://127.0.0.1:$RTSP_PORT/$RTSP_PATH
   runOnDemandRestart: yes 
```

## Did you attach the server logs?

yes
[rtsp-simple-server.log](https://github.com/aler9/rtsp-simple-server/files/8356352/rtsp-simple-server.log)

And also a INFO log from console direct that might give more details?
[rtsp-simple-server-INFO.log](https://github.com/aler9/rtsp-simple-server/files/8356380/rtsp-simple-server-INFO.log)

## Did you attach a network dump?

no

**Comment by aler9** [comment] 2022-04-10 16:40
Hello, the problem is a recurring one and a duplicate of #795:

```
2022/03/26 22:02:03 INF [RTSP] [conn 127.0.0.1:57788] closed (invalid SDP: unable to parse track 2: unable to get clock rate: attribute 'rtpmap' not found)
```

FFmpeg doesn't provide the clock rate of the subtitle track, therefore it's impossible for the server to generate the corresponding RTCP receiver report, that tells the server how the streaming is going:

```
m=text 0 RTP/AVP 98
a=control:streamid=2
```

This should be

```
m=text 0 RTP/AVP 98
a=control:streamid=2
a=rtpmap:98 subtitles/90000
```

Please contact the FFmpeg server.

**Closed by aler9** 2022-04-10 16:40 UTC
