### ISSUE TITLE
HLS-LL error [muxer] destroyed (muxer error: wrong nal_ref_idc)

### ISSUE THREAD

**Issue by t3therdev** [aler9/rtsp-simple-server#969] opened 2022-06-04 06:03 UTC
## Which version are you using?

v0.19.0

## Which operating system are you using?

- [ ] Windows amd64 standard

## Describe the issue

Pull stream from our server via RTSP TCP. 
Connect HLS LL client browser (edge or chrome)
Other cameras directly work to hls-ll on this RTSPSS instance, but all our server streams do not. 
RTSP proxy works fine. HLS-LL is the issue. 

error is: [muxer camera2] destroyed (muxer error: wrong nal_ref_idc)

tried multiple hlspartduration settings per your notes as well. 

debug logs attached

## Did you attach the server logs?

ye
[rtsp-simple-server-error.log](https://github.com/aler9/rtsp-simple-server/files/8837128/rtsp-simple-server-error.log)

**Comment by aler9** [comment] 2022-06-04 09:27
duplicate of #966

**Closed by aler9** 2022-06-04 09:27 UTC
