### ISSUE TITLE
crash when proxing HLS

### ISSUE THREAD

**Issue by zhaibin18** [aler9/rtsp-simple-server#558] opened 2021-09-07 23:41 UTC
## Which version are you using?

v0.17.3

## Which operating system are you using?

OS

- [ *] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [ *] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

crash with two path in config file
paths:
  test1:
    source: http://site1/1.m3u8
  test2:
     source: http://site2/1.m3u8

## Describe how to replicate the issue

2021/09/07 23:35:34 I [0/0] rtsp-simple-server v0.17.3
2021/09/07 23:35:34 I [0/0] [path test1] created
2021/09/07 23:35:34 I [0/0] [path test2] created
2021/09/07 23:35:34 I [0/0] [path test2] [hls source] started
2021/09/07 23:35:34 D [0/0] [path test2] [hls source] downloading primary playlist http://site2/1.m3u8
2021/09/07 23:35:34 I [0/0] [RTSP] UDP/RTP listener opened on :8000
2021/09/07 23:35:34 I [0/0] [RTSP] UDP/RTCP listener opened on :8001
2021/09/07 23:35:34 I [0/0] [RTSP] TCP listener opened on :8554
2021/09/07 23:35:34 I [0/0] [RTMP] listener opened on :1935
2021/09/07 23:35:34 I [0/0] [HLS] listener opened on :8888
2021/09/07 23:35:34 I [0/0] [path test1] [hls source] started
2021/09/07 23:35:34 D [0/0] [path test1] [hls source] downloading primary playlist http://site1/1.m3u8
2021/09/07 23:35:34 D [0/0] [path test1] [hls source] downloading segment http://site1/1631057668-1-1613619454.hls.ts
2021/09/07 23:35:34 D [0/0] [path test2] [hls source] downloading segment http://site2/1631057678-1-1613621216.hls.ts
2021/09/07 23:35:39 D [0/0] [path test1] [hls source] downloading segment http://site1/1631057678-1-1613619455.hls.ts
2021/09/07 23:35:39 I [0/0] [path test1] [hls source] ready
2021/09/07 23:35:40 D [0/0] [path test2] [hls source] downloading segment http://site2/1631057688-1-1613621217.hls.ts
2021/09/07 23:35:40 I [0/0] [path test2] [hls source] ready
2021/09/07 23:35:44 D [0/0] [path test2] [hls source] downloading segment http://site2/1631057698-1-1613621218.hls.ts
2021/09/07 23:35:44 D [0/0] [path test1] [hls source] downloading segment http://site1/1631057688-1-1613619456.hls.ts
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x9da770]

goroutine 11 [running]:
github.com/aler9/rtsp-simple-server/internal/hls.(*Client).processSegment(0xc0000200f0, 0xcaba38, 0xc00006a180, 0xc00360c000, 0x9c6330, 0xad8000, 0x0, 0x0)
        /s/internal/hls/client.go:803 +0x130
github.com/aler9/rtsp-simple-server/internal/hls.(*Client).runProcessor(0xc0000200f0, 0xcaba38, 0xc00006a180, 0x0, 0x0)
        /s/internal/hls/client.go:730 +0x7e
github.com/aler9/rtsp-simple-server/internal/hls.(*Client).runInner.func2(0xc00006e2a0, 0xc0000200f0, 0xcaba38, 0xc00006a180)
        /s/internal/hls/client.go:487 +0x3f
created by github.com/aler9/rtsp-simple-server/internal/hls.(*Client).runInner
        /s/internal/hls/client.go:487 +0x114

## Did you attach a network dump?

no

**Comment by aler9** [comment] 2021-09-08 07:05
Hello, i don't think that the issue is related to the fact that there are two paths in the configuration file, i think that it is related to the segments of one of your streams. Please try to replicate the issue with a single path and attach the last .ts file that is written in the log (i.e. http://site1/1631057688-1-1613619456.hls.ts).

**Comment by zhaibin18** [comment] 2021-09-08 07:25
yes, you are right,there is something wrong with site2.
[rtsp_server_dump.zip](https://github.com/aler9/rtsp-simple-server/files/7126744/rtsp_server_dump.zip)


2021/09/08 07:22:16 I [0/0] rtsp-simple-server v0.17.3
2021/09/08 07:22:16 I [0/0] [path test2] created
2021/09/08 07:22:16 I [0/0] [path test2] [hls source] started
2021/09/08 07:22:16 D [0/0] [path test2] [hls source] downloading primary playlist http://site2/1.m3u8
2021/09/08 07:22:16 I [0/0] [RTSP] UDP/RTP listener opened on :8000
2021/09/08 07:22:16 I [0/0] [RTSP] UDP/RTCP listener opened on :8001
2021/09/08 07:22:16 I [0/0] [RTSP] TCP listener opened on :8554
2021/09/08 07:22:16 I [0/0] [RTMP] listener opened on :1935
2021/09/08 07:22:16 I [0/0] [HLS] listener opened on :8888
2021/09/08 07:22:16 D [0/0] [path test2] [hls source] downloading segment http://site2/1631085676-1-1613624016.hls.ts
2021/09/08 07:22:19 I [0/0] [HLS] [conn 10.1.2.222:8120] GET /test2/
2021/09/08 07:22:19 I [0/0] [HLS] [muxer test2] created
2021/09/08 07:22:19 I [0/0] [HLS] [muxer test2] ERR: no one is publishing to path 'test2'
2021/09/08 07:22:19 I [0/0] [HLS] [muxer test2] destroyed
2021/09/08 07:22:21 D [0/0] [path test2] [hls source] downloading segment http://site2/1631085686-1-1613624017.hls.ts
2021/09/08 07:22:22 I [0/0] [path test2] [hls source] ready
2021/09/08 07:22:24 I [0/0] [HLS] [conn 10.1.2.222:8120] GET /test2/
2021/09/08 07:22:24 I [0/0] [HLS] [muxer test2] created
2021/09/08 07:22:24 I [0/1] [HLS] [muxer test2] is converting into HLS
2021/09/08 07:22:24 I [0/1] [HLS] [conn 10.1.2.222:8120] GET /test2/index.m3u8
2021/09/08 07:22:24 I [0/1] [HLS] [conn 10.1.2.222:8120] GET /test2/stream.m3u8
2021/09/08 07:22:26 I [0/1] [HLS] [conn 10.1.2.222:8120] GET /test2/1631085744.ts
2021/09/08 07:22:27 D [0/1] [path test2] [hls source] downloading segment http://site2/1631085695-1-1613624018.hls.ts
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x9da770]

goroutine 22 [running]:
github.com/aler9/rtsp-simple-server/internal/hls.(*Client).processSegment(0xc00008e0f0, 0xcaba38, 0xc00029b280, 0xc000600000, 0x9c6854, 0xad8000, 0x0, 0x0)
        /s/internal/hls/client.go:803 +0x130
github.com/aler9/rtsp-simple-server/internal/hls.(*Client).runProcessor(0xc00008e0f0, 0xcaba38, 0xc00029b280, 0x0, 0x0)
        /s/internal/hls/client.go:730 +0x7e
github.com/aler9/rtsp-simple-server/internal/hls.(*Client).runInner.func2(0xc000082660, 0xc00008e0f0, 0xcaba38, 0xc00029b280)
        /s/internal/hls/client.go:487 +0x3f
created by github.com/aler9/rtsp-simple-server/internal/hls.(*Client).runInner
        /s/internal/hls/client.go:487 +0x114

**Comment by aler9** [comment] 2021-09-30 09:51
Thanks for providing a TS file that allowed to replicate the issue, this allowed to fix a bug in both `go-astits` and `rtsp-simple-server`.
The problem is fixed in main and will be added to the next release.

**Comment by aler9** [comment] 2021-10-03 14:27
added in v0.17.4

**Closed by aler9** 2021-10-03 14:27 UTC
Labels: bug

**Comment by zhaibin18** [comment] 2021-10-04 00:34
there is no sound and can not enable.
![image](https://user-images.githubusercontent.com/6645145/135778938-93b2a268-cfc2-4be6-8404-0fd021ba822e.png)
