### ISSUE TITLE
HLS not working on Mobile Phone IOS or Android when there's no audio track

### ISSUE THREAD

**Issue by Tabarane** [aler9/rtsp-simple-server#816] opened 2022-02-04 16:30 UTC
## Which version are you using?

v0.17.116

## Which operating system are you using?

- [X] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [X] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description
using old version from rtsp-simple-server "0.17.11" HLS on mobile phone works normally , latest version it keep loading nothing show up

## rtsp-simple-server log show that connection is made and is sending frames but still nothing showing up on mobile phone, we test with safari , chrome , Samsung internet

**Comment by calebcoverdale** [comment] 2022-02-18 03:35
I can also confirm I am having the same issues on my end with newer version of  iPhone OS + HLS. 
Issue doesn't happen on iPadOS, or macOS from what I have seen running the latest iOS15 Betas, but the issue persists specifically on iPhone.

**Comment by Tabarane** [comment] 2022-02-18 11:23
does anyone need logs or something to help us fix this issue on latest version, i just did test with 017.17 and still the same issue exist :( just let me know how to help

**Comment by aler9** [comment] 2022-02-18 11:31
Hello @Tabarane , the issue you described is too generic and i wasn't able to replicate it. Please provide at least:

* configuration
* server logs with `logLevel: debug`
* name of the software you're using to publish

**Comment by Tabarane** [comment] 2022-02-18 11:35
`###############################################
# HLS parameters

# disable support for the HLS protocol.
hlsDisable: no
# address of the HLS listener.
hlsAddress: :8888
# by default, HLS is generated only when requested by a user.
# this option allows to generate it always, avoiding the delay between request and generation.
hlsAlwaysRemux: no
# number of HLS segments to generate.
# increasing segments allows more buffering,
# decreasing segments decreases latency.
hlsSegmentCount: 3
# minimum duration of each segment.
# the final segment duration is also influenced by the interval between IDR frames,
# since the server changes the segment duration to include at least a IDR frame in each one.
hlsSegmentDuration: 1s
# Maximum size of each segment.
# This prevents RAM exhaustion.     
hlsSegmentMaxSize: 50M
# value of the Access-Control-Allow-Origin header provided in every HTTP response.
# This allows to play the HLS stream from an external website.
hlsAllowOrigin: '*'
###############################################`

This is HLS configuration, attaching Log file in 5min , and i use Safari IOS to view, and Publish of the path is below
`  video0:
   runOnDemand: ffmpeg -hide_banner -re -stream_loop -1 -i video0.webm -vf "drawtext='fontfile=./Robot.ttf:fontsize=14:fontcolor=yellow:text='%{localtime}':box=1:boxcolor=black@1:boxborderw=2:x=2:y=2" -vcodec h264_qsv -preset veryfast -r 25 -g 30 -s 1280x720 -b:v 1000k -max_muxing_queue_size 1024 -f rtsp rtsp://127.0.0.1:$RTSP_PORT/$RTSP_PATH 
   runOnDemandRestart: yes`
   
` ffmpeg version n4.4-18-gc813f5e343`

**Comment by aler9** [comment] 2022-02-18 20:29
Please try this configuration and let me know if it works. I tested it on Android and iOS and i couldn't find any problem.

```yml
paths:
  video0:
   runOnDemand: >
     ffmpeg -hide_banner -re -f lavfi -i testsrc=duration=1000:size=1280x720:rate=30
     -pix_fmt yuv420p -c:v libx264 -preset ultrafast -b:v 500k -max_muxing_queue_size 1024
     -f rtsp rtsp://127.0.0.1:$RTSP_PORT/$RTSP_PATH
   runOnDemandRestart: yes
```

**Comment by Tabarane** [comment] 2022-02-19 09:15
@aler9 same issue, i have attached new log after new setting you mentioned also i have uploaded my config file for you in case it will help, i might not have big experience in FFMPEG parameter , please note im not testing on Windows environments, the HLS transmission is working fine with my old parameter for video0 with older version of RTSP SIMPLE SERVER, like 0.17.11

my current tests is onRTSP SIMPLE SERVER 0.17.17
[server.log](https://github.com/aler9/rtsp-simple-server/files/8101782/server.log)
[config.yml.txt](https://github.com/aler9/rtsp-simple-server/files/8101783/config.yml.txt)

**Comment by aler9** [comment] 2022-02-19 10:16
The configuration i posted above works perfectly for me. Since it was not possible to replicate the problem, we can't assert that the problem depends on the server. It may depend on any of the components you're using to stream (OS, ffmpeg, video file, phones).
Nothing can be done here until you're able to correctly identify the problem.

I suggest you to take the exact configuration i posted above (with testsrc) and test it apart from your setup. When it works (and i'm sure it works), you can progressively add the rest of your configuration until you find the issue.

**Comment by Tabarane** [comment] 2022-02-19 10:20
@aler9 ok i will start doing it step by step until i figure why, i will try not with file i will try with re-streaming RTSP or Proxy mode via HLS and will note all in the Server log and share again, my issue that it works with older version in same setup same scenario, i even had my friend phone which is Andriod phone and has the same issue, OS im trying on Ubuntu & Windows 10, will try also different FFMPEG in case it reached this level

Thanks alot will get back soon i hope here, Maybe @calebcoverdale can you share your files Log and it might help us

**Comment by aler9** [comment] 2022-02-19 10:31
The only difference between v0.17.11 and v0.17.12 is that the progressive mode of hls.js was enabled. But hls.js is used only on browsers that don't support natively HLS, therefore the change doesn't influence Safari and iPhone.

**Comment by akunz** [comment] 2022-02-21 15:34
From my understanding since some time an EXT-X-PROGRAM-DATE-TIME tag has been required in every live/linear media playlist. Please check point 8.4 in the [specification](https://developer.apple.com/documentation/http_live_streaming/http_live_streaming_hls_authoring_specification_for_apple_devices). I guess this will solve the problem on newer devices.

**Comment by aler9** [comment] 2022-02-21 15:36
@akunz thank you very much for the tip, i'll produce a nightly release ASAP.

**Comment by aler9** [comment] 2022-02-21 16:20
I added the `EXT-X-PROGRAM-DATE-TIME` tag (thanks @akunz, i just needed that for a project in my job that needs syncing between video and metadata, i thought i needed to implement [timed metadata](https://github.com/video-dev/hls.js/issues/159) and spend hours on the issue, this solved everything in less than 5 mins), please test this nightly release and let me know if there's any difference:
[rtsp-simple-server_v0.17.17-15-g0508552_darwin_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/8110748/rtsp-simple-server_v0.17.17-15-g0508552_darwin_amd64.tar.gz)
[rtsp-simple-server_v0.17.17-15-g0508552_linux_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/8110749/rtsp-simple-server_v0.17.17-15-g0508552_linux_amd64.tar.gz)
[rtsp-simple-server_v0.17.17-15-g0508552_linux_arm64v8.tar.gz](https://github.com/aler9/rtsp-simple-server/files/8110750/rtsp-simple-server_v0.17.17-15-g0508552_linux_arm64v8.tar.gz)
[rtsp-simple-server_v0.17.17-15-g0508552_linux_armv6.tar.gz](https://github.com/aler9/rtsp-simple-server/files/8110752/rtsp-simple-server_v0.17.17-15-g0508552_linux_armv6.tar.gz)
[rtsp-simple-server_v0.17.17-15-g0508552_linux_armv7.tar.gz](https://github.com/aler9/rtsp-simple-server/files/8110754/rtsp-simple-server_v0.17.17-15-g0508552_linux_armv7.tar.gz)
[rtsp-simple-server_v0.17.17-15-g0508552_windows_amd64.zip](https://github.com/aler9/rtsp-simple-server/files/8110758/rtsp-simple-server_v0.17.17-15-g0508552_windows_amd64.zip)

**Comment by Tabarane** [comment] 2022-02-21 16:22
@aler9 testing right now, same setting as mentioned above

**Comment by Tabarane** [comment] 2022-02-21 16:27
@aler9 my first test on IOS has same results as before , w will test different devices and give feedback, do you need network dump? and debug log?

**Comment by Tabarane** [comment] 2022-02-21 16:33
Ok, now this is very strange behavior , i requested video from rtsp server, safari keep showing the loading progress and black screen, while i stopped the server and started it again, the video in safari started directly after the restart 

i can record phone screen and share video if this will help you or let me know how i can show you which ever data you need, i apologies if i seems like spamming but i highly appreciate your help with this app, it just an amazing project mate

**Comment by aler9** [comment] 2022-02-21 16:36
@Tabarane are you sure you tried with testsrc, before trying with video0.webm?

**Comment by Tabarane** [comment] 2022-02-21 16:40
@aler9 100% , in windows browser it works , but with mobile phone same behavior
![image](https://user-images.githubusercontent.com/28815281/154996023-decb148e-bb66-458a-a923-a885b1379bd1.png)

**Comment by Tabarane** [comment] 2022-02-21 16:55
on windows still , same when i shutdown server and start it again then video loads up, i think i need to gather network dump and test in linux before you can take more approach , i want to give you as much details as needed specially if you revert hls support to 17.11 this what i can think of :(

**Comment by Curid** [comment] 2022-02-21 18:38
@Tabarane  You could find the exact commit that introduced the bug.
https://www.git-tower.com/learn/git/faq/git-bisect/

**Comment by Tabarane** [comment] 2022-02-22 08:05
@aler9 after a lot of testing, i have downloaded every release from 0.17.11 till 0.17.14 and HLS over Phones was working perfectly, its when i downloaded 0.17.15 where HLS over phones has stopped working and introduced the issue.

the behavior is same, when HLS url requested , it shows black screen loading with no video, BUT if i closed the server and start it again, it takes around 5 second and the HLS video will start playing in Safari

Do you need traffic dump and debug log from this attempt?

**Comment by akunz** [comment] 2022-02-22 11:34
I can confirm the described problem as well. My first thouth was about the EXT-X-PROGRAM-DATE-TIME tag when I read this issue. I still think the tag is needed and useful, even it is not the solution to fix the current problem. Thank you so much for adding this additional tag. I did some research on the segments generated by rtsp-simple-server and there is a difference in the generation of audio between version 0.17.14 and the nightly release 0.17.17-15. FFmpeg also shows some warnings about timestamps, but I guess the problem is caused by the audio. The sample configuration using testsrc does not generate audio and it looks like rtsp-simple-server handles audio differently in this situation. When we add audio to the testsrc command, it works fine for me, even in newer Safari browser and some other players.

**Comment by Tabarane** [comment] 2022-02-22 11:37
@akunz can you advice how to test with audio using ffmpeg testsrc? 
below is my config im testing with, if you can add the audio part it would be great so i can test also
```
  video00:
   runOnDemand: ffmpeg -hide_banner -re -stream_loop -1 -f lavfi -i testsrc=duration=1000:size=1280x720:rate=30 -pix_fmt yuv420p -c:v libx264 -preset ultrafast -b:v 500k -max_muxing_queue_size 1024 -f rtsp rtsp://127.0.0.1:$RTSP_PORT/$RTSP_PATH
   runOnDemandRestart: yes
```

**Comment by akunz** [comment] 2022-02-22 11:53
You can add audio (sine wave) by the following option:

`-f lavfi -i sine=frequency=1000:sample_rate=48000`

Your config should look like this:

```
  video00:
   runOnDemand: ffmpeg -hide_banner -re -stream_loop -1 -f lavfi -i testsrc=duration=1000:size=1280x720:rate=30 -f lavfi -i sine=frequency=1000:sample_rate=48000 -pix_fmt yuv420p -c:v libx264 -preset ultrafast -b:v 500k -max_muxing_queue_size 1024 -f rtsp rtsp://127.0.0.1:$RTSP_PORT/$RTSP_PATH
   runOnDemandRestart: yes
```

**Comment by Tabarane** [comment] 2022-02-22 13:24
@akunz @aler9 i can confirm, when i added  `-f lavfi -i sine=frequency=1000:sample_rate=48000` video started to play normally over HLS, even if it was my own video files, just added the audio feed made the server response to IOS safari and it was working , test was made on 0.17.17

**Comment by aler9** [comment] 2022-03-20 15:43
This issue has been solved.... it was caused by this terrible Golang behavior:

```go
package main

import "fmt"

type Track interface{}
type trackImpl struct{}

func testFunc(tr Track) {
	if tr != nil {
		fmt.Println("track is not nil")
	} else {
		fmt.Println("track is nil")
	}
}

func main() {
	var tr *trackImpl = nil
	testFunc(tr)
}
```

even though `tr` is nil, this code prints "track is not nil" :man_facepalming:

**Comment by aler9** [comment] 2022-03-20 15:46
Please try this nightly release and let me know if it works:
[rtsp-simple-server_v0.17.17-38-g99f3215_linux_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/8311579/rtsp-simple-server_v0.17.17-38-g99f3215_linux_amd64.tar.gz)
[rtsp-simple-server_v0.17.17-38-g99f3215_darwin_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/8311580/rtsp-simple-server_v0.17.17-38-g99f3215_darwin_amd64.tar.gz)
[rtsp-simple-server_v0.17.17-38-g99f3215_windows_amd64.zip](https://github.com/aler9/rtsp-simple-server/files/8311582/rtsp-simple-server_v0.17.17-38-g99f3215_windows_amd64.zip)
[rtsp-simple-server_v0.17.17-38-g99f3215_linux_arm64v8.tar.gz](https://github.com/aler9/rtsp-simple-server/files/8311583/rtsp-simple-server_v0.17.17-38-g99f3215_linux_arm64v8.tar.gz)
[rtsp-simple-server_v0.17.17-38-g99f3215_linux_armv6.tar.gz](https://github.com/aler9/rtsp-simple-server/files/8311584/rtsp-simple-server_v0.17.17-38-g99f3215_linux_armv6.tar.gz)
[rtsp-simple-server_v0.17.17-38-g99f3215_linux_armv7.tar.gz](https://github.com/aler9/rtsp-simple-server/files/8311585/rtsp-simple-server_v0.17.17-38-g99f3215_linux_armv7.tar.gz)

**Comment by Tabarane** [comment] 2022-03-20 16:39
Tested on Windows , and working fine on IOS without audio track, now working as expected as before

**Comment by Wheemer** [comment] 2022-03-20 17:54
Working very well now, thanks so much. This is a very nice program, good work.

**Comment by Tabarane** [comment] 2022-03-21 09:49
Tested on Debian Based, issue still exist unless we add fake sound parameter

**Comment by aler9** [comment] 2022-04-10 16:21
The fix has been added in v0.18.0. Regarding the Debian bug, please open a new issue and provide details.

**Closed by aler9** 2022-04-10 16:21 UTC
Labels: bug

**Comment by jamieduk** [comment] 2022-11-04 18:03
I have no sound it is disabled (muted) in all browsers on load by default how do i fix this bug? im using linux pre compiled binary?

**Comment by aler9** [comment] 2023-01-08 21:58
@jamieduk audio must be disabled in order for the video to play automatically, it's a restriction imposed by browsers. You can read more here https://developer.chrome.com/blog/autoplay/
