### ISSUE TITLE
Fetching Bitrate via Metrics or HTTP API

### ISSUE THREAD

**Issue by leon-wbr** [aler9/rtsp-simple-server#796] opened 2022-01-28 14:08 UTC
## Describe the feature

I would like to integrate with [NOALBS](https://github.com/715209/nginx-obs-automatic-low-bitrate-switching), which requires a way to read out the bitrate available. However, it doesn't seem that rtsp-simple-server has such a stats page.

I can try submitting a pull request if someone gives some guidance on where to integrate this.

**Comment by aler9** [comment] 2022-01-28 16:39
duplicate of #734

**Closed by aler9** 2022-01-28 16:39 UTC
