### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by InSpectrumed** [aler9/rtsp-simple-server#193] opened 2021-01-24 20:12 UTC
rtsp-simple-server v0.12.2

My system is Ubuntu 18.04.5

I need to publish more than 2000 threads to the server
I have an error:

2021/01/24 21:58:16 [1009/614/0] [client 127.0.0.1:44922] connected
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x7e57f0]

goroutine 39 [running]:
github.com/aler9/rtsp-simple-server/internal/client.(*Client).log(0xc008f468c0, 0x952506, 0x9, 0x0, 0x0, 0x0)
	/s/internal/client/client.go:187 +0x30
github.com/aler9/rtsp-simple-server/internal/client.New(0x2136, 0x2540be400, 0x2540be400, 0x0, 0x0, 0x0, 0xc000182870, 0xc0001d41b8, 0xc00018c1c0, 0xc0001d2050, ...)
	/s/internal/client/client.go:170 +0x21a
github.com/aler9/rtsp-simple-server/internal/clientman.(*ClientManager).run(0xc0001d4140)
	/s/internal/clientman/clientman.go:104 +0x4b7
created by github.com/aler9/rtsp-simple-server/internal/clientman.New
	/s/internal/clientman/clientman.go:82 +0x1b3

**Comment by aler9** [comment] 2021-01-26 20:16
Hello, please use the latest version (v0.13.3) and let me know if the bug is still present.

**Comment by InSpectrumed** [comment] 2021-01-27 16:44
2021/01/27 18:35:05 [I] [0/0/0] rtsp-simple-server v0.13.3

**System: Ubuntu 18.04.5**

I can add 2000 clints with jpegenc.

I also have an error:

2021/01/27 18:32:58 [I] [1011/0/0] [client 127.0.0.1:38418] connected (plain)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x7f394d]

goroutine 21 [running]:
github.com/aler9/gortsplib.(*ServerConn).NetConn(...)
	/go/pkg/mod/github.com/aler9/gortsplib@v0.0.0-20210119134354-d9b819e85e9b/serverconn.go:242
github.com/aler9/rtsp-simple-server/internal/client.(*Client).log(0xc00185fc80, 0x1, 0x95f8aa, 0xe, 0xc000236db0, 0x1, 0x1)
	/s/internal/client/client.go:131 +0x2d
github.com/aler9/rtsp-simple-server/internal/client.New(0xc000236e00, 0x216a, 0x2540be400, 0x0, 0x0, 0x0, 0xc000094930, 0xc0000ae2a8, 0xc0000a2180, 0x0, ...)
	/s/internal/client/client.go:109 +0x1ae
github.com/aler9/rtsp-simple-server/internal/clientman.(*ClientManager).run(0xc0000ae240)
	/s/internal/clientman/clientman.go:113 +0x5bc
created by github.com/aler9/rtsp-simple-server/internal/clientman.New
	/s/internal/clientman/clientman.go:77 +0x19a


**System: Windows 10**

I added 3000 clients with jpegenc.

This error does not exist.

**Comment by aler9** [comment] 2021-01-31 11:31
Hello, can you post your GStreamer pipeline in order to allow me to replicate the issue? thanks

**Comment by eLvErDe** [comment] 2021-03-18 17:24
Hello aler9:

Just did some testing and the crash can still be triggered quite easily with 0.15.0.

Regards

**Comment by aler9** [comment] 2021-03-19 12:42
@eLvErDe the issue should be fixed, it was caused by two problems

* the server didn't reported errors when accepting clients
* the server didn't touched a limit on the maximum number of open connections (file descriptors), that defaulted to 1024 on Ubuntu 18.04

Please try the attached nightly release, try to connect a big number of clients (in my case, i tested with 1500) and let me know if it works.

[rtsp-simple-server_v0.15.0-14-g3243510_windows_amd64.zip](https://github.com/aler9/rtsp-simple-server/files/6171103/rtsp-simple-server_v0.15.0-14-g3243510_windows_amd64.zip)
[rtsp-simple-server_v0.15.0-14-g3243510_linux_arm64v8.tar.gz](https://github.com/aler9/rtsp-simple-server/files/6171105/rtsp-simple-server_v0.15.0-14-g3243510_linux_arm64v8.tar.gz)
[rtsp-simple-server_v0.15.0-14-g3243510_linux_arm7.tar.gz](https://github.com/aler9/rtsp-simple-server/files/6171108/rtsp-simple-server_v0.15.0-14-g3243510_linux_arm7.tar.gz)
[rtsp-simple-server_v0.15.0-14-g3243510_linux_arm6.tar.gz](https://github.com/aler9/rtsp-simple-server/files/6171110/rtsp-simple-server_v0.15.0-14-g3243510_linux_arm6.tar.gz)
[rtsp-simple-server_v0.15.0-14-g3243510_linux_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/6171112/rtsp-simple-server_v0.15.0-14-g3243510_linux_amd64.tar.gz)
[rtsp-simple-server_v0.15.0-14-g3243510_darwin_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/6171113/rtsp-simple-server_v0.15.0-14-g3243510_darwin_amd64.tar.gz)

**Comment by eLvErDe** [comment] 2021-03-19 12:59
Hey,

Thanks a lot for addressing the issue! Sadly it is not starting anymore:
`rtsp-simple-server[255537]: ERR: invalid argument`

But already knew it would end up like this: You're not allowed to raise RLIMIT yourself, only root can do this, and when running as a systemd service, even as root, this is not permitted either.
Imho you should attempt to raise and log a warning if this is not possible.

Regards, Adam

**Comment by eLvErDe** [comment] 2021-03-19 13:03
Adding `LimitNOFILE=infinity` in systemd file works, I guess it somehow inhibits the call you're attempting

**Comment by aler9** [comment] 2021-03-19 13:23
@eLvErDe i edited the patch to TRY to raise ulimit, and not to fail in case of errors. Anyway, the server now reports error during accept(), let me know if there's something else that can be done.
[rtsp-simple-server_v0.15.0-14-g6acc1f9_windows_amd64.zip](https://github.com/aler9/rtsp-simple-server/files/6171342/rtsp-simple-server_v0.15.0-14-g6acc1f9_windows_amd64.zip)
[rtsp-simple-server_v0.15.0-14-g6acc1f9_linux_arm64v8.tar.gz](https://github.com/aler9/rtsp-simple-server/files/6171343/rtsp-simple-server_v0.15.0-14-g6acc1f9_linux_arm64v8.tar.gz)
[rtsp-simple-server_v0.15.0-14-g6acc1f9_linux_arm7.tar.gz](https://github.com/aler9/rtsp-simple-server/files/6171344/rtsp-simple-server_v0.15.0-14-g6acc1f9_linux_arm7.tar.gz)
[rtsp-simple-server_v0.15.0-14-g6acc1f9_linux_arm6.tar.gz](https://github.com/aler9/rtsp-simple-server/files/6171346/rtsp-simple-server_v0.15.0-14-g6acc1f9_linux_arm6.tar.gz)
[rtsp-simple-server_v0.15.0-14-g6acc1f9_linux_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/6171347/rtsp-simple-server_v0.15.0-14-g6acc1f9_linux_amd64.tar.gz)
[rtsp-simple-server_v0.15.0-14-g6acc1f9_darwin_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/6171348/rtsp-simple-server_v0.15.0-14-g6acc1f9_darwin_amd64.tar.gz)

**Comment by eLvErDe** [comment] 2021-03-19 13:31
Thanks, I'll try to get some feedbacks but you might need to wait until Monday to get a complete one.

**Comment by dorinclisu** [comment] 2021-03-21 09:01
I think I'm getting the same problem, it's not triggered by something specific, it works for a while with about 100 sources and after a few hours it crashes. RAM and CPU usage never exceed 50%. But after crash the CPU stays at 100%.
```
2021-03-20T22:20:33.899520093Z error: invalid memory address or nil pointer dereference
2021-03-20T22:20:33.903603146Z segmentation violation code=0x1 addr=0x10 pc=0x6f181a]
2021-03-20T22:20:33.906150629Z [running]:
2021-03-20T22:20:33.908177732Z 0xbb796a53d9f, 0xcb1800, 0x0, 0xc024904f00, 0x5, 0x200e)
2021-03-20T22:20:33.909469592Z github.com/aler9/gortsplib.(*ClientConn).backgroundPlayTCP
```

I would say, more important that solving this particular crash is making sure that the process exits on unrecoverable errors. In my case the process just hangs so docker does not know to automatically restart.

**Comment by bbnp91** [comment] 2021-03-22 07:25
I had the same problem running v0.14 Have updated to the nightly release v0.15-14, and set up a loadtest of 2000 subs pulling a 64kb audio stream. Server is running on a E2 2vCPU, 2Gb Mem. Incredible performance.

**Comment by eLvErDe** [comment] 2021-03-22 14:29
Hello,

No more crashes with the GIT version for us, thanks !

**Comment by aler9** [comment] 2021-03-23 21:09
added in v0.15.1:
* the server try to raise the maximum number of open files
* even in case of errors, the server doesn't crash, but print errors

**Closed by aler9** 2021-03-23 21:09 UTC
Labels: bug

**Comment by dorinclisu** [comment] 2021-04-11 13:08
@aler9 
The problem is not solved in 0.15.4, I am still getting exactly the same error. The process hangs with CPU at 100%.

```
2021-04-11T08:50:52.546331155Z [I] [57/0/25] [client A.B.C.D:54120] is reading from path 'path123', 1 track with tcp
2021-04-11T08:50:52.551534607Z error: invalid memory address or nil pointer dereference
2021-04-11T08:50:52.552695839Z segmentation violation code=0x1 addr=0x10 pc=0x6f481a]
2021-04-11T08:50:52.553570163Z [running]:
2021-04-11T08:50:52.557716154Z 0x8edfa007d14e, 0xcc5880, 0x0, 0xc00da32800, 0x5, 0x2710)
2021-04-11T08:50:52.559239354Z 0xc002159c10)
2021-04-11T08:50:52.560232505Z github.com/aler9/gortsplib.(*ClientConn).backgroundPlayTCP
```

**Comment by aler9** [comment] 2021-04-11 13:28
@dorinclisu this is a segment violation but it's unrelated from this issue, open a dedicated issue and describe how to replicate

**Comment by dorinclisu** [comment] 2021-04-12 08:27
Opened here https://github.com/aler9/rtsp-simple-server/issues/348
